import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { KnowledgeLayout, type SectionItem } from "@/components/KnowledgeLayout";
import { buildPageMetadata } from "@/lib/site";
import { cn } from "@/lib/cn";

export const metadata = buildPageMetadata({ title: "安全测试实战手册", description: "面向 Web 与 API 的安全测试实战手册，覆盖攻击面、认证、授权、输入验证、业务安全和上线自查。", path: "/knowledge/security-testing-manual", tags: ["安全测试", "OWASP", "API 安全", "越权", "Web 安全"] });

const sections: SectionItem[] = [
  { id: "overview", label: "测试目标" }, { id: "scope", label: "攻击面" }, { id: "auth", label: "认证会话" }, { id: "access", label: "越权测试" }, { id: "input", label: "输入输出" }, { id: "api", label: "API 安全" }, { id: "business", label: "业务安全" }, { id: "tools", label: "工具流程" }, { id: "report", label: "漏洞交付" }, { id: "checklist", label: "上线清单" },
];

const surfaceRows = [["身份入口", "登录、注册、找回密码", "暴力破解、账号枚举、会话固定"], ["用户数据", "个人资料、订单、文件", "水平越权、敏感信息泄露"], ["管理后台", "配置、审批、报表", "垂直越权、默认账号"], ["接口与网关", "REST、GraphQL、Webhook", "鉴权缺失、参数篡改、重放"], ["第三方依赖", "支付、短信、对象存储", "回调伪造、密钥和权限错误"]];
const authRows = [["登录失败", "密码或验证码错误", "提示不暴露账号是否存在，失败次数受控"], ["暴力破解", "短时间连续请求", "限速、验证码、临时锁定与审计有效"], ["Token", "缺失、过期、篡改", "统一拒绝，不返回内部异常细节"], ["退出登录", "旧 Token 再次访问", "令牌或服务端会话已失效"], ["密码重置", "复用链接、篡改用户 ID", "一次性令牌、短有效期、绑定目标用户"]];
const accessRows = [["水平越权", "用户 A 修改订单 ID 查询用户 B 的订单", "只能访问自己的资源"], ["垂直越权", "普通用户调用管理端接口", "服务端按角色或权限拒绝"], ["字段越权", "请求体传入 role=admin", "忽略或拒绝不可写字段"], ["批量操作", "一次提交多个资源 ID", "逐个校验资源归属"]];
const vulnerabilityRows = [["注入", "SQL、命令、模板注入", "参数化查询；错误不回显底层语句"], ["XSS", "反射、存储、DOM XSS", "按上下文编码，富文本使用白名单"], ["文件上传", "伪造后缀、双扩展名、超大文件", "校验内容和大小，隔离存储，不可执行"], ["SSRF", "URL 参数访问内网或云元数据", "限制协议、域名、IP 段和重定向"], ["配置泄露", "debug、错误页、目录列表", "关闭调试信息，不暴露密钥和堆栈"]];

export default function SecurityTestingManualPage() {
  return <div className="mx-auto max-w-5xl animate-fade-in">
    <Link href="/knowledge" target="_blank" rel="noopener noreferrer" className="mb-8 inline-flex items-center gap-2 text-sm text-text-secondary hover:text-neon-cyan transition-colors"><ArrowLeft className="h-4 w-4" />返回知识库</Link>
    <KnowledgeLayout sections={sections}>
      <header className="mb-10"><h1 className="mb-3 bg-gradient-to-r from-neon-cyan to-neon-purple bg-clip-text text-3xl font-bold text-transparent md:text-4xl">安全测试实战手册</h1><p className="mb-6 text-lg text-text-secondary">不靠“扫一遍工具”碰运气，而是从攻击面、权限边界和业务风险出发，验证系统是否真正守得住。</p><div className="flex flex-wrap gap-6 text-sm text-text-secondary"><span>10 个章节</span><span>Web + API</span><span>适用于测试、开发与产品负责人</span></div></header>
      <section id="overview" data-knowledge-section className="mb-14"><Header icon="🛡️" title="安全测试的目标" badge="保护资产，而非刷漏洞数" /><Card title="先问：我们到底在保护什么？"><p>安全测试的核心不是证明系统“绝对安全”，而是识别攻击者最可能利用的路径，在上线前把高影响、低成本利用的问题消掉。</p><List items={["账户与权限：别人能否冒充用户，或获得不该有的能力？", "业务资产：金额、库存、优惠券、积分、订单能否被篡改或重复使用？", "敏感数据：个人资料、Token、密钥和内部配置会不会泄露？", "可用性：恶意请求能否拖垮服务、耗尽资源或绕过限流？"]} /></Card><Card title="测试边界"><List items={["只在已授权的系统、环境、账号和时间窗口内测试。", "优先使用测试环境、测试数据和非真实支付渠道。", "发现高危问题立即停止扩大验证并同步负责人。"]} /></Card></section>
      <section id="scope" data-knowledge-section className="mb-14"><Header icon="🗺️" title="攻击面梳理" badge="知道入口，才知道从哪测" /><Table title="常见攻击面" headers={["区域", "典型入口", "优先检查"]} rows={surfaceRows} /><Card title="最小威胁建模"><List ordered items={["列出资产：账号、订单、资金、文件、后台权限、密钥。", "列出入口：页面、接口、后台、任务、回调和第三方集成。", "思考攻击者目标：偷数据、越权、薅优惠、伪造回调还是拖垮系统？", "给风险按影响和发生概率排序，先测高风险路径。"]} /></Card></section>
      <section id="auth" data-knowledge-section className="mb-14"><Header icon="🔑" title="认证与会话安全" badge="你是谁，凭什么证明" /><Table title="身份认证测试矩阵" headers={["场景", "测试动作", "期望结果"]} rows={authRows} /><Card title="额外检查"><List items={["Cookie 应设置 HttpOnly、Secure 与合适的 SameSite 策略。", "Token 不应放在 URL 查询参数中，避免进入日志、历史记录和 Referer。", "登录、改密、绑定设备等敏感操作应有适当的二次校验。"]} /></Card></section>
      <section id="access" data-knowledge-section className="mb-14"><Header icon="🚧" title="授权与越权测试" badge="最常见，也最容易漏" /><Table title="权限测试要覆盖资源、角色和字段" headers={["类型", "验证方式", "安全预期"]} rows={accessRows} /><Card title="实操顺序"><List ordered items={["准备至少两个普通用户和一个管理员账号，资源归属要不同。", "分别用不同 Token 请求相同接口，只改资源 ID 或归属字段。", "检查读取、修改、删除、导出、批量操作是否都做了服务端校验。", "不能只看前端按钮是否隐藏；真正的判定必须发生在服务端。"]} /></Card></section>
      <section id="input" data-knowledge-section className="mb-14"><Header icon="🧪" title="输入、输出与常见漏洞" badge="所有外部输入都不可信" /><Table title="高频验证点" headers={["类别", "测试关注", "安全要求"]} rows={vulnerabilityRows} /><Card title="输入验证的正确位置"><List items={["前端校验提升体验，但不是安全边界；攻击者可以绕过页面直接请求接口。", "服务端对类型、长度、格式、枚举值和业务状态做白名单校验。", "错误信息对用户要可读，对攻击者要克制：不回传 SQL、调用栈、绝对路径或密钥。"]} /></Card></section>
      <section id="api" data-knowledge-section className="mb-14"><Header icon="🔌" title="API 安全测试" badge="移动端与前端都挡不住裸接口" /><div className="grid gap-4 md:grid-cols-2"><Card title="请求侧"><List items={["每个敏感接口都需要认证和资源级授权。", "签名、时间戳、nonce 与重放保护应覆盖关键交易。", "分页大小、查询范围和导出任务需要限制。", "调试接口、Swagger 和过期版本不应错误暴露到公网。"]} /></Card><Card title="响应侧"><List items={["按最小化原则返回字段，不返回密码、密钥、内部状态。", "错误码一致，避免通过响应差异枚举账号或资源。", "不信任客户端传回的价格、角色和归属信息。", "高成本请求要有鉴权、限流、超时和审计。"]} /></Card></div></section>
      <section id="business" data-knowledge-section className="mb-14"><Header icon="💳" title="业务安全" badge="规则被绕过，比技术漏洞更贵" /><Card title="电商与交易场景必测"><List items={["改价格、改数量、改优惠券 ID：服务端必须重新计算金额。", "支付回调重复、乱序或伪造：订单状态和资金流水必须幂等且可验证来源。", "并发抢库存、领券、签到：不能超卖、超发或重复记账。", "退款、取消、确认收货等状态不能跳级，权限和时间窗口必须受控。"]} /></Card><Card title="一个判断标准"><p>如果攻击者不需要绕过技术防线，只要篡改一个正常参数就能获得不当利益，这就是业务安全问题。用例要从“用户会不会这样点”升级到“恶意用户会怎样构造请求”。</p></Card></section>
      <section id="tools" data-knowledge-section className="mb-14"><Header icon="🧰" title="工具与测试流程" badge="工具帮助发现，人工负责判断" /><div className="grid gap-4 md:grid-cols-2"><Card title="常用工具"><List items={["浏览器 DevTools：看请求、Cookie、CORS、安全响应头。", "Burp Suite：代理拦截、重放、参数对比和授权测试。", "Postman：沉淀可复用 API 安全用例与断言。", "OWASP ZAP：在授权范围内辅助发现常见 Web 配置问题。"]} /></Card><Card title="推荐流程"><List ordered items={["读业务与资产，先做攻击面和风险排序。", "手工验证认证、越权、关键业务规则。", "工具辅助发现输入、配置和响应问题。", "复现并记录最小证据，评估真实影响。", "修复后回归，把高价值用例沉淀进自动化。"]} /></Card></div></section>
      <section id="report" data-knowledge-section className="mb-14"><Header icon="📝" title="漏洞交付与复测" badge="可复现、可判断、可修复" /><Card title="一份有效漏洞报告至少包含"><List items={["标题与等级：清楚表达什么问题、影响什么资产。", "受影响范围：环境、接口、账号角色、前置条件。", "最小复现步骤：请求方法、参数变化、可观察结果。", "影响说明：攻击者实际能读取、修改或造成什么损失。", "修复建议：给出原则与方向。", "复测结论：原路径被阻断，正常业务没有回归。"]} /></Card></section>
      <section id="checklist" data-knowledge-section className="mb-14"><Header icon="✅" title="上线前 10 分钟安全自查" badge="优先消灭高风险漏项" /><div className="grid gap-4 md:grid-cols-3"><Card title="身份与权限"><List items={["默认账号已关闭或改密", "Token 和 Cookie 配置正确", "用户只能访问自己的资源", "管理接口有服务端鉴权"]} /></Card><Card title="数据与配置"><List items={["响应不含密钥和敏感字段", "生产关闭 debug 与详细错误", "上传文件隔离且不可执行", "密钥来自安全配置，不在代码中"]} /></Card><Card title="业务与运营"><List items={["金额和库存由服务端计算", "支付回调可验签且幂等", "关键接口有限流与审计", "高危问题已有修复与复测证据"]} /></Card></div></section>
    </KnowledgeLayout>
  </div>;
}

function Header({ icon, title, badge }: { icon: string; title: string; badge: string }) { return <div className="mb-5 flex items-center gap-3 border-b-2 border-space-border pb-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-neon-cyan/10 text-lg">{icon}</div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold text-text-primary">{title}</h2><span className="rounded-full bg-neon-cyan/10 px-2 py-0.5 text-[10px] font-medium text-neon-cyan">{badge}</span></div></div>; }
function Card({ title, children }: { title?: string; children: React.ReactNode }) { return <div className="card-glow mb-4 rounded-xl p-5 text-sm leading-7 text-text-secondary">{title && <h3 className="mb-3 text-base font-bold text-text-primary">{title}</h3>}{children}</div>; }
function List({ items, ordered = false }: { items: readonly string[]; ordered?: boolean }) { const Tag = ordered ? "ol" : "ul"; return <Tag className={cn("mt-3 space-y-2 pl-5", ordered ? "list-decimal" : "list-disc")}>{items.map((item) => <li key={item}>{item}</li>)}</Tag>; }
function Table({ title, headers, rows }: { title: string; headers: string[]; rows: string[][] }) { return <Card title={title}><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-space-border">{headers.map((header) => <th key={header} className="bg-neon-cyan/5 px-4 py-3 text-left font-semibold text-text-primary">{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row[0]} className="border-b border-space-border/50 last:border-b-0">{row.map((cell) => <td key={cell} className="px-4 py-2.5 text-xs leading-relaxed">{cell}</td>)}</tr>)}</tbody></table></div></Card>; }
