import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import { KnowledgeLayout, type SectionItem } from "@/components/KnowledgeLayout";
import { buildPageMetadata } from "@/lib/site";
import { cn } from "@/lib/cn";

export const metadata = buildPageMetadata({ title: "Web 功能测试实战教程", description: "以商城登录、商品列表、下单、支付和退款为案例，系统学习 Web 页面、业务流程、权限、文件、缓存和 DevTools 测试。", path: "/knowledge/web-functional-testing", tags: ["Web 测试", "功能测试", "浏览器", "DevTools", "业务流程"] });
const sections: SectionItem[] = [{ id: "model", label: "Web 测试模型" }, { id: "forms", label: "表单登录" }, { id: "lists", label: "列表搜索分页" }, { id: "flow", label: "交易流程" }, { id: "permission", label: "权限测试" }, { id: "files", label: "文件与链接" }, { id: "cache", label: "缓存与刷新" }, { id: "devtools", label: "DevTools 定位" }, { id: "practice", label: "练习与检查" }];
const formRows = [["账号", "空值、格式、长度、前后空格、大小写", "当账号为空时，页面提示必填且不发送登录请求"], ["密码", "空值、边界长度、可见切换、粘贴", "当密码错误时，页面提示安全且不暴露账号状态"], ["验证码", "过期、错误、重复使用、刷新", "当验证码过期时，登录失败并允许重新获取"], ["提交", "回车、双击、加载中、超时", "当连续点击登录时，只发出一次有效请求"]];
const devRows = [["Elements", "元素状态、禁用属性、错误提示", "按钮看似禁用但仍能触发"], ["Network", "方法、参数、响应、Timing", "页面失败究竟有没有请求"], ["Console", "脚本错误与警告", "点击后前端异常中断"], ["Application", "Cookie、Storage、缓存", "登录态、购物车或旧资源异常"]];

export default function WebFunctionalTestingPage() { return <div className="mx-auto max-w-5xl animate-fade-in">
      <Link href="/knowledge/defect-management-analysis" className="mb-8 inline-flex items-center gap-2 text-sm text-text-secondary transition-colors hover:text-neon-cyan"><ArrowLeft className="h-4 w-4" />返回 Bug 管理与缺陷分析</Link>
  <KnowledgeLayout sections={sections} searchPlaceholder="搜索 Web 测试关键词...">
    <header className="mb-10"><div className="mb-3 font-mono text-[10px] uppercase tracking-[0.22em] text-neon-cyan">Main Track / Tutorial 06</div><h1 className="mb-3 bg-gradient-to-r from-neon-cyan to-neon-purple bg-clip-text text-3xl font-bold text-transparent md:text-4xl">Web 功能测试实战教程</h1><p className="mb-6 text-lg leading-8 text-text-secondary">不只检查按钮能不能点，还要验证浏览器中的交互、请求、状态、权限与后端数据共同完成正确业务。</p><div className="flex flex-wrap gap-6 text-sm text-text-secondary"><span>9 个章节</span><span>商城 Web 全流程</span><span>页面 + 请求 + 数据</span></div></header>
    <section id="model" data-knowledge-section className="mb-14"><SectionHeader number="01" title="建立 Web 功能测试模型" badge="用户看到的是整条链路" /><FlowFigure id="web-model" title="一次下单跨越多个验证面" items={[["页面交互", "输入与反馈"], ["浏览器状态", "Cookie 与缓存"], ["HTTP 请求", "参数与响应"], ["业务数据", "订单与库存"]]} /><Card title="每次操作至少问四件事"><BulletList items={["操作前：用户、数据和页面处于什么状态？", "操作中：控件是否可用，重复操作会怎样？", "操作后：页面提示、跳转和展示是否正确？", "系统侧：请求、业务码和关键数据是否一致？"]} /></Card><Callout>页面显示“成功”不是终点。创建订单接口即使返回 HTTP 200，也要继续核对业务码、订单状态、金额与库存。</Callout></section>
    <section id="forms" data-knowledge-section className="mb-14"><SectionHeader number="02" title="从登录表单练输入与提交" badge="字段规则 + 组合状态" /><TableCard title="登录表单测试点" headers={["对象", "覆盖角度", "当……时，……用例"]} rows={formRows} /><Card title="可执行步骤"><BulletList ordered items={["记录字段必填、格式、长度和默认值。", "用等价类与边界值准备输入。", "组合账号、密码、验证码的合法与非法状态。", "使用点击、回车和重复点击提交。", "核对错误定位、已填内容保留和请求是否发送。"]} /></Card></section>
    <section id="lists" data-knowledge-section className="mb-14"><SectionHeader number="03" title="测试商品列表、搜索和分页" badge="结果集必须稳定一致" /><ListFigure /><TableCard title="列表类页面检查" headers={["功能", "重点", "用例示例"]} rows={[["搜索", "精确、模糊、空词、特殊字符", "当搜索不存在的商品时，展示空状态而不是旧结果"], ["筛选", "单选、组合、重置、无结果", "当价格与品牌组合筛选时，结果同时满足两个条件"], ["排序", "升降序、相同值、空值", "当按价格升序时，同价商品分页间不重复丢失"], ["分页", "首页、末页、页大小、数据变化", "当删除末页最后一条数据时，回到有效页码"]]} /><Callout>分页正确不只看页码。要验证总数、页大小、排序稳定性，以及翻页时没有重复和遗漏。</Callout></section>
    <section id="flow" data-knowledge-section className="mb-14"><SectionHeader number="04" title="验证登录、下单、支付、退款主流程" badge="主路径与异常路径" /><FlowFigure id="trade-flow" title="商城核心交易流程" items={[["登录", "建立身份"], ["下单", "锁定价格库存"], ["支付", "确认资金结果"], ["退款", "回退资金与状态"]]} /><div className="grid gap-4 md:grid-cols-2"><Card title="主路径"><BulletList items={["当账号有效时，登录成功并回到原访问页。", "当库存充足时，提交后生成一笔金额正确的订单。", "当支付成功时，订单更新并可以查看支付记录。", "当满足退款条件时，退款申请成功并展示进度。"]} /></Card><Card title="异常路径"><BulletList items={["当登录过期时，下单被拦截并可恢复操作。", "当库存刚好被抢完时，不创建无效订单。", "当支付超时时，不把未知结果展示为失败并允许重复扣款。", "当重复退款时，只保留一笔有效申请。"]} /></Card></div></section>
    <section id="permission" data-knowledge-section className="mb-14"><SectionHeader number="05" title="验证页面、接口和数据权限" badge="隐藏按钮不等于安全" /><PermissionFigure /><Card title="越权测试步骤"><BulletList ordered items={["准备用户 A 和用户 B，并分别创建订单。", "用 A 登录并正常打开自己的订单。", "把 URL 或请求中的订单 ID 换成 B 的订单。", "确认页面拒绝、接口拒绝且不返回 B 的数据。", "检查日志是否记录越权尝试，数据没有被修改。"]} /></Card><Card title="关键用例"><BulletList items={["当游客访问订单详情时，系统要求登录且不泄露订单摘要。", "当用户 A 请求用户 B 的订单时，系统拒绝并返回安全提示。", "当普通用户伪造客服退款操作时，接口拒绝且订单不变。"]} /></Card></section>
    <section id="files" data-knowledge-section className="mb-14"><SectionHeader number="06" title="测试上传、下载、链接和跳转" badge="文件也有业务边界" /><TableCard title="退款凭证与下载测试" headers={["对象", "测试点", "预期"]} rows={[["上传类型", "允许图片，拒绝脚本与伪装扩展名", "前后端都校验，提示明确"], ["上传大小", "0 B、上限内、等于上限、超过上限", "边界规则一致，不残留半文件"], ["文件名", "中文、空格、超长、特殊字符", "安全保存与显示，不产生路径穿越"], ["下载", "权限、名称、类型、内容完整性", "仅授权用户可下载正确文件"], ["跳转", "站内、支付沙箱、返回地址", "目标正确，失败可回到安全页面"]]} /><Callout>上传测试只能使用无害测试文件。不要上传真实恶意程序，也不要在没有授权的环境做攻击性验证。</Callout></section>
    <section id="cache" data-knowledge-section className="mb-14"><SectionHeader number="07" title="处理刷新、前进后退和缓存" badge="浏览器状态会改变结果" /><StateFigure /><Card title="容易遗漏的浏览器行为"><BulletList items={["当刷新订单确认页时，不重复创建订单。", "当支付后点击后退时，不回到可再次支付的旧状态。", "当退出登录时，前进后退不能看到敏感订单内容。", "当商品价格更新时，刷新后展示新价格，提交以服务端校验为准。", "当多标签页同时退款时，状态能同步或明确提示冲突。"]} /></Card></section>
    <section id="devtools" data-knowledge-section className="mb-14"><SectionHeader number="08" title="使用 DevTools 定位页面问题" badge="从现象到证据" /><TableCard title="四个常用面板" headers={["面板", "检查内容", "适合定位"]} rows={devRows} /><Card title="定位“提交订单无反应”"><BulletList ordered items={["打开 Network 和 Console，清空本轮记录。", "点击一次提交并确认按钮状态。", "没有请求时检查表单校验与 Console。", "有请求时检查方法、参数、HTTP 状态与业务码。", "记录 request_id，再核对订单和库存数据。", "用同一证据链编写缺陷，不凭页面现象归因。"]} /></Card></section>
    <section id="practice" data-knowledge-section className="mb-14"><SectionHeader number="09" title="完成一次 Web 商城回归" badge="按真实工作执行" /><Card title="练习"><BulletList ordered items={["准备游客、普通用户 A、用户 B 和客服四种身份。", "按“当……时，……”格式编写 12 条用例。", "覆盖登录表单、商品搜索、分页和下单。", "覆盖重复支付、退款、越权与浏览器前进后退。", "选择一个失败场景，用 DevTools 建立证据链。", "输出通过、失败、阻塞和剩余风险。"]} /></Card><div className="grid gap-4 md:grid-cols-3"><ChecklistCard title="页面" items={["控件状态正确", "边界提示明确", "跳转路径正确", "刷新后状态合理"]} /><ChecklistCard title="业务" items={["主流程闭环", "异常可恢复", "权限不越界", "重复操作幂等"]} /><ChecklistCard title="证据" items={["请求可追踪", "业务结果已核对", "数据一致", "缺陷可复现"]} /></div><NextLink text="Web 流程清楚后，下一篇把订单、支付和退款拆成可穷举的状态流转规则。" href="/knowledge/business-state-machine-testing" label="继续学习业务状态流转测试" /></section>
  </KnowledgeLayout>
</div>; }

function SectionHeader({ number, title, badge }: { number: string; title: string; badge: string }) { return <div className="mb-5 flex items-center gap-3 border-b-2 border-space-border pb-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-neon-cyan/10 font-mono text-xs text-neon-cyan">{number}</div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold text-text-primary">{title}</h2><span className="rounded-full bg-neon-cyan/10 px-2 py-0.5 text-[10px] font-medium text-neon-cyan">{badge}</span></div></div>; }
function Card({ title, children }: { title?: string; children: React.ReactNode }) { return <div className="card-glow mb-4 rounded-xl p-5 text-sm leading-7 text-text-secondary">{title && <h3 className="mb-3 text-base font-bold text-text-primary">{title}</h3>}{children}</div>; }
function BulletList({ items, ordered = false }: { items: readonly string[]; ordered?: boolean }) { const Tag = ordered ? "ol" : "ul"; return <Tag className={cn("mt-3 space-y-2 pl-5", ordered ? "list-decimal" : "list-disc")}>{items.map((item) => <li key={item}>{item}</li>)}</Tag>; }
function TableCard({ title, headers, rows }: { title: string; headers: readonly string[]; rows: readonly string[][] }) { return <Card title={title}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b border-space-border">{headers.map((header) => <th key={header} className="bg-neon-cyan/5 px-4 py-3 text-left font-semibold text-text-primary">{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.join("-")} className="border-b border-space-border/50 last:border-b-0">{row.map((cell, index) => <td key={`${cell}-${index}`} className="px-4 py-2.5 text-xs leading-relaxed">{cell}</td>)}</tr>)}</tbody></table></div></Card>; }
function Callout({ children }: { children: React.ReactNode }) { return <div className="mb-4 border-l-2 border-neon-cyan bg-neon-cyan/5 px-5 py-4 text-sm leading-7 text-text-secondary">{children}</div>; }
function FlowFigure({ id, title, items }: { id: string; title: string; items: readonly (readonly [string, string])[] }) { return <figure className="card-glow mb-4 rounded-xl p-5" aria-labelledby={id}><figcaption id={id} className="mb-5 text-sm font-bold text-text-primary">{title}</figcaption><div className="grid gap-2 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{items.map((item, index) => <div key={item[0]} className="contents"><div className="rounded-lg border border-space-border bg-space-card/50 p-4 text-center"><strong className="block text-sm text-text-primary">{item[0]}</strong><span className="mt-2 block text-xs text-text-secondary">{item[1]}</span></div>{index < items.length - 1 && <ArrowRight className="mx-auto hidden h-4 w-4 text-neon-cyan md:block" />}</div>)}</div></figure>; }
function ListFigure() { return <FlowFigure id="list-title" title="列表结果由四个条件共同决定" items={[["查询词", "搜什么"], ["筛选", "保留什么"], ["排序", "先显示什么"], ["分页", "本页显示什么"]]} />; }
function PermissionFigure() { return <FlowFigure id="permission-title" title="权限必须贯穿三层" items={[["页面入口", "只展示可用操作"], ["接口鉴权", "拒绝伪造请求"], ["数据隔离", "只能访问授权记录"], ["审计记录", "关键操作可追溯"]]} />; }
function StateFigure() { return <FlowFigure id="browser-state-title" title="同一页面可能同时存在多份状态" items={[["服务端", "订单真实状态"], ["页面内存", "当前交互状态"], ["本地存储", "登录与购物车"], ["浏览器缓存", "资源与响应"]]} />; }
function ChecklistCard({ title, items }: { title: string; items: readonly string[] }) { return <Card title={title}><ul className="space-y-3">{items.map((item) => <li key={item} className="flex items-start gap-2"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-neon-cyan" /><span>{item}</span></li>)}</ul></Card>; }
function NextLink({ text, href, label }: { text: string; href: string; label: string }) { return <div className="mt-8 flex flex-wrap items-center justify-between gap-4 border-y border-space-border py-6"><p className="text-sm text-text-secondary">{text}</p><Link href={href} className="inline-flex items-center gap-2 text-sm text-neon-cyan">{label}<ArrowRight className="h-4 w-4" /></Link></div>; }
