import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import { KnowledgeLayout, type SectionItem } from "@/components/KnowledgeLayout";
import { buildPageMetadata } from "@/lib/site";

export const metadata=buildPageMetadata({title:"测试资产平台与规则引擎开发教程",description:"从需求文档解析、测试资产模型和版本追溯，到规则校验、AI 草稿评审、数据存储、权限审计与平台演进。",path:"/knowledge/test-platform-development",tags:["测试平台","规则引擎","测试开发","用例管理"]});
const sections:SectionItem[]=[{id:"goal",label:"平台目标"},{id:"architecture",label:"系统架构"},{id:"ingestion",label:"文档接入"},{id:"model",label:"资产模型"},{id:"rules",label:"规则引擎"},{id:"review",label:"评审流转"},{id:"api",label:"接口设计"},{id:"operations",label:"权限与运维"},{id:"evolution",label:"演进路线"},{id:"practice",label:"练习清单"}];

export default function TestPlatformPage(){return <div className="mx-auto max-w-5xl animate-fade-in"><Link href="/knowledge/tutorials?track=test-development" className="mb-8 inline-flex items-center gap-2 text-sm text-text-secondary hover:text-neon-cyan"><ArrowLeft className="h-4 w-4"/>返回测试开发强化支线</Link><KnowledgeLayout sections={sections} searchPlaceholder="搜索平台、规则引擎、评审与追溯...">
<Header/>
<S id="goal" n="01" t="平台首先解决资产失控，不是展示更多按钮" b="单一事实来源"><Table title="平台要消除的四类问题" headers={["问题","平台能力"]} rows={[["用例散落在多份 Excel","统一版本、模块和编号索引"],["修改靠截图和口头确认","评审状态、修改记录和责任留痕"],["AI 一次生成大量草稿","批量入库、规则校验和人工审批"],["下个版本无法判断哪些还能用","需求规则、来源标识和版本差异追溯"]]}/><Callout>平台不是为了取代 Excel，而是让需求、规则、风险、用例和评审拥有稳定关系。需要对外交付时仍可以导出文件。</Callout></S>
<S id="architecture" n="02" t="按接入、资产、规则、评审和交付分层" b="职责清楚"><Flow items={[["文档接入","SRS/表格/图片"],["资产服务","规则/风险/用例"],["规则引擎","覆盖/冲突/重复"],["评审工作流","草稿到定稿"],["交付与度量","导出/报告/看板"]]}/><Card title="一套可起步的技术边界"><List items={["后端提供文档、版本、资产、评审和校验 API。","关系型数据库保存版本、元数据与评审记录；大字段或源文件独立存储。","前端围绕版本与模块浏览、筛选、编辑和下钻。","异步任务处理大文档解析、AI 生成和批量校验。","AI 模型通过网关接入，密钥只存服务端环境变量或密钥系统。"]}/></Card></S>
<S id="ingestion" n="03" t="文档接入必须先证明没有漏内容" b="解析也是被测功能"><Table title="接入流水线" headers={["步骤","产物","校验"]} rows={[["上传","原始文件与哈希","格式、大小、重复文件"],["解析","段落、表格、图片和位置","元素计数、失败清单"],["结构重建","章节树与阅读顺序","章节连续、表格归属"],["规则提取","rule_id、原文和状态","来源可点击、冲突可见"],["人工确认","确定规则与待确认项","确认人、时间和版本留痕"]]}/><Card title="不能静默跳过"><p>图片 OCR 失败、表格无法解析或段落为空时，任务应进入“部分成功”并列出缺失元素。平台不能用一个绿色“解析完成”掩盖不完整输入。</p></Card></S>
<S id="model" n="04" t="用稳定主键连接版本与资产" b="不要把整行文本当身份"><Table title="核心实体" headers={["实体","关键字段"]} rows={[["Version","version_id、父版本、状态、创建时间"],["RequirementRule","rule_id、版本、来源位置、规则正文、状态"],["Risk","risk_id、触发条件、等级、来源模式"],["TestCase","case_id、版本、模块、rule_ids、来源、优先级、评审状态"],["Review","对象、前后快照、结论、意见、评审人、时间"],["ValidationRun","规则集版本、结果、失败项、执行时间"]]}/><Callout>同一业务用例跨版本演进时，要保留稳定关联与版本快照。仅用 Excel 行号或标题作为主键，改名后追溯会断裂。</Callout></S>
<S id="rules" n="05" t="规则引擎既检查错误，也检查缺失" b="注册表驱动"><Table title="规则类型" headers={["类型","示例","结果"]} rows={[["Schema","必填字段、枚举和数据类型","直接通过或失败"],["完整性","有用例的模块必须存在规则注册表","缺失时阻断"],["追溯","确定规则至少关联一条候选或正式用例","输出未覆盖规则"],["冲突","数值、权限、状态与需求不一致","标记人工裁决"],["重复","编号重复、标题或步骤高度相似","建议合并"],["分布","优先级与来源分布明显异常","告警而非自动改写"]]}/><Card title="规则集也要版本化"><List items={["保存 rule_set_version 与适用项目。","每次执行保留输入快照和结果。","新增规则先用历史样本回放，观察误报。","规则为空或未适用任何模块时发出空转告警。"]}/></Card></S>
<S id="review" n="06" t="AI 草稿必须经过显式状态流转" b="候选不等于定稿"><Flow items={[["AI 草稿","来源可见"],["机器校验","结构与规则"],["人工评审","接受/修改/拒绝"],["已通过","等待版本定稿"],["正式资产","可交付与统计"]]}/><Table title="评审记录" headers={["字段","作用"]} rows={[["before / after","看见修改了什么"],["decision","接受、修改、拒绝或待确认"],["reason_code","错误类型可统计并回流"],["reviewer","责任落到具体身份"],["evidence","关联规则、需求或缺陷"],["reviewed_at","形成可审计时间线"]]}/></S>
<S id="api" n="07" t="API 围绕版本化资源设计" b="前端不直接碰文件"><Table title="最小 API 集" headers={["方法","路径","职责"]} rows={[["POST","/versions/{v}/documents","上传并创建解析任务"],["GET","/versions/{v}/rules","查询规则与待确认项"],["GET/PUT","/versions/{v}/cases","查询或保存候选用例"],["POST","/versions/{v}/validations","运行指定版本规则集"],["POST","/cases/{id}/reviews","提交评审结论"],["GET","/versions/{v}/exports","生成交付文件与版本报告"]]}/><Card title="批量接口要考虑"><List items={["逐行错误和部分成功，不只返回整体失败。","幂等键防止重试产生重复用例。","冲突策略明确：覆盖、跳过还是生成新版本。","大任务返回 task_id，支持进度、取消、超时和重试。"]}/></Card></S>
<S id="operations" n="08" t="平台自己也要满足权限、审计与恢复" b="质量平台不能成为风险源"><Table title="上线前重点" headers={["方面","要求"]} rows={[["权限","项目、版本、模块和评审角色最小授权"],["密钥","模型 API Key 不入库明文、不返回前端、不进日志"],["审计","导入、编辑、评审、导出和规则变更全部留痕"],["备份","数据库、源文件和规则集有一致性备份与恢复演练"],["并发","多人编辑冲突可见，避免后保存覆盖先保存"],["降级","AI 不可用时仍可浏览、编辑、校验和导出已有资产"]]}/></S>
<S id="evolution" n="09" t="按价值逐步演进，不一开始做大而全" b="先治理，再智能"><Table title="演进路线" headers={["阶段","能力","完成标准"]} rows={[["V1 资产可见","导入、查询、编辑、版本和导出","团队只有一份事实来源"],["V2 质量可控","规则引擎、评审状态与审计","草稿无法绕过门禁定稿"],["V3 协作可用","多用户、权限、冲突与通知","责任和进度可追踪"],["V4 AI 增强","规则提取、候选生成和失败回流","人工接受率和错误类型可量化"],["V5 生态连接","缺陷、CI、执行平台和质量看板","资产真正参与发布决策"]]}/></S>
<S id="practice" n="10" t="实现一个最小可用资产平台" b="练习与检查清单"><Card title="练习"><List ordered items={["设计 Version、Rule、Case、Review 和 ValidationRun 数据模型。","实现 SRS 上传、元素计数和部分失败报告。","完成用例查询、保存和版本快照 API。","实现完整性、追溯、冲突和去重四类规则。","建立 AI 草稿→机器校验→人工评审→定稿状态流转。","验证权限、审计、备份恢复与 AI 不可用降级。"]}/></Card><Check items={["文档解析结果可核对","资产拥有稳定 ID 和版本","规则能发现缺失","AI 草稿不能直接定稿","评审前后差异可追溯","密钥不暴露","备份与恢复已验证","平台失败不破坏原始资产"]}/><Next/></S>
</KnowledgeLayout></div>}

function Header(){return <header className="mb-10"><div className="mb-3 font-mono text-[10px] uppercase tracking-[0.22em] text-neon-cyan">SDET Track / Platform Engineering</div><h1 className="mb-3 bg-gradient-to-r from-neon-cyan to-neon-purple bg-clip-text text-3xl font-bold text-transparent md:text-4xl">测试资产平台与规则引擎开发教程</h1><p className="text-lg leading-8 text-text-secondary">把散落的需求、规则、用例和评审纳入同一套版本化平台，让机器校验和人工决策都能留下证据。</p></header>}
function S({id,n,t,b,children}:{id:string;n:string;t:string;b:string;children:React.ReactNode}){return <section id={id} data-knowledge-section className="mb-14"><div className="mb-5 flex items-center gap-3 border-b-2 border-space-border pb-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-neon-cyan/10 font-mono text-xs text-neon-cyan">{n}</div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold text-text-primary">{t}</h2><span className="rounded-full bg-neon-cyan/10 px-2 py-0.5 text-[10px] text-neon-cyan">{b}</span></div></div>{children}</section>}
function Card({title,children}:{title?:string;children:React.ReactNode}){return <div className="card-glow mb-4 rounded-xl p-5 text-sm leading-7 text-text-secondary">{title&&<h3 className="mb-3 text-base font-bold text-text-primary">{title}</h3>}{children}</div>}
function List({items,ordered=false}:{items:string[];ordered?:boolean}){const T=ordered?"ol":"ul";return <T className={`mt-3 space-y-2 pl-5 ${ordered?"list-decimal":"list-disc"}`}>{items.map(x=><li key={x}>{x}</li>)}</T>}
function Table({title,headers,rows}:{title:string;headers:string[];rows:string[][]}){return <Card title={title}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b border-space-border">{headers.map(x=><th key={x} className="bg-neon-cyan/5 px-4 py-3 text-left text-text-primary">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.join()} className="border-b border-space-border/50">{r.map((x,i)=><td key={x+i} className="px-4 py-2.5 text-xs leading-relaxed">{x}</td>)}</tr>)}</tbody></table></div></Card>}
function Callout({children}:{children:React.ReactNode}){return <div className="mb-4 border-l-2 border-neon-cyan bg-neon-cyan/5 px-5 py-4 text-sm leading-7 text-text-secondary">{children}</div>}
function Flow({items}:{items:string[][]}){return <Card title="测试资产平台主链路"><div className="grid gap-3 md:grid-cols-5">{items.map((x,i)=><div key={x[0]} className={`rounded-lg border p-4 ${i===2?"border-neon-cyan/50 bg-neon-cyan/10":"border-space-border bg-space-card/50"}`}><b className="block text-xs text-text-primary">{x[0]}</b><span className="text-[11px]">{x[1]}</span></div>)}</div></Card>}
function Check({items}:{items:string[]}){return <Card title="完成检查">{items.map(x=><div key={x} className="mb-2 flex gap-2"><CheckCircle2 className="mt-1 h-4 w-4 text-neon-cyan"/>{x}</div>)}</Card>}
function Next(){return <div className="mt-8 flex justify-end border-y border-space-border py-6"><Link href="/knowledge/testing-engineer-roadmap#test-development" className="inline-flex items-center gap-2 text-sm text-neon-cyan">返回测试开发强化支线<ArrowRight className="h-4 w-4"/></Link></div>}
