import Link from "next/link";
import {ArrowLeft, CheckCircle2} from "lucide-react";
import { KnowledgeLayout, type SectionItem } from "@/components/KnowledgeLayout";
import { buildPageMetadata } from "@/lib/site";

export const metadata=buildPageMetadata({title:"权限、数据隔离与访问审计测试教程",description:"从菜单、按钮、URL、接口与数据范围构建权限矩阵，覆盖水平垂直越权、会话残留、导出泄露与运维访问审计。",path:"/knowledge/access-control-testing",tags:["权限测试","越权测试","数据隔离","堡垒机","安全测试"]});
const sections:SectionItem[]=[{id:"model",label:"权限模型"},{id:"entries",label:"四层入口"},{id:"data",label:"数据范围"},{id:"bypass",label:"越权测试"},{id:"session",label:"变更与会话"},{id:"export",label:"导出与附件"},{id:"audit",label:"访问审计"},{id:"cases",label:"用例矩阵"},{id:"practice",label:"练习清单"}];

export default function AccessControlPage(){return <div className="mx-auto max-w-5xl animate-fade-in"><Link href="/knowledge/tutorials?track=business-testing" className="mb-8 inline-flex items-center gap-2 text-sm text-text-secondary hover:text-neon-cyan"><ArrowLeft className="h-4 w-4"/>返回业务与用例设计模块</Link><KnowledgeLayout sections={sections} searchPlaceholder="搜索权限、越权、数据范围与审计...">
<Header/>
<S id="model" n="01" t="权限测试要同时验证功能与数据" b="能做什么 × 能看什么"><Table title="授权模型" headers={["维度","问题","例子"]} rows={[["身份认证","你是谁","登录用户、Token、设备会话"],["功能权限","能做什么","菜单、查询、编辑、审核、导出"],["数据权限","能操作哪些记录","集团、本级及以下、本级、个人"],["资源归属","这条数据属于谁","机构、部门、个人、租户"],["审计约束","谁在何时做了什么","操作日志、审批、会话录像"]]}/><Callout>页面上看不到按钮，不等于没有权限。真正的授权判断必须在服务端对功能、数据归属和当前身份一起完成。</Callout></S>
<S id="entries" n="02" t="菜单、按钮、URL、接口四层都要测" b="隐藏不是拒绝"><Table title="四层防线" headers={["入口","有权用户","无权用户"]} rows={[["菜单","可见并可进入","不可见"],["按钮","可见且操作成功","不可见或禁用"],["URL 直达","页面正常加载","拒绝访问且不泄露内容"],["接口直调","按授权范围返回或写入","返回拒绝结果且业务不生效"]]}/><Card title="固定测试动作"><List items={["先用有权账号完成一次，记录 URL、接口和资源 ID。","切换无权账号，不经过页面直接访问相同入口。","分别修改角色、机构、资源 ID 和操作参数。","同时断言响应状态、响应内容和业务是否真正生效。"]}/></Card></S>
<S id="data" n="03" t="把角色与数据归属画成矩阵" b="每条数据对号入座"><Table title="常见数据范围" headers={["角色范围","应可见","不应可见"]} rows={[["集团","全集团授权数据","明确排除的敏感域"],["本级及以下","本机构和下级机构","上级与平级机构"],["本级","本机构","上级、下级与平级"],["个人","本人数据","任何其他用户数据"]]}/><Card title="每个矩阵格至少验证"><List items={["列表是否出现。","详情是否可打开且字段完整。","编辑、删除、审批是否可执行。","统计和金额合计是否只计算授权范围。","导出文件是否与页面范围一致。"]}/></Card></S>
<S id="bypass" n="04" t="水平越权与垂直越权必须分别验证" b="拒绝且零泄露"><Table title="两类越权" headers={["类型","动作","典型风险"]} rows={[["水平越权","同级用户替换资源 ID 访问他人记录","个人或机构数据泄露"],["垂直越权","低权限用户直调管理员接口","执行审核、删除或配置操作"],["跨租户越权","替换 tenant_id 或关联键","租户隔离失效"]]}/><Card title="双重判据"><List items={["访问被拒绝：按产品约定返回 403、404 或统一错误。","内容不泄露：响应体、文件名、数量、金额和状态都不包含目标资源信息。","操作不生效：数据库、消息、审计日志中没有越权产生的业务结果。"]}/></Card><Callout>只断言状态码不够。有的接口返回错误提示，却已经写入数据库；有的接口拒绝页面访问，却在响应体里带回完整业务数据。</Callout></S>
<S id="session" n="05" t="权限变更后要验证生效时机" b="不要自己猜时限"><Table title="变更场景" headers={["场景","要核对的会话"]} rows={[["移除功能权限","当前会话、刷新后、重新登录后"],["改变数据范围","列表、详情、接口缓存与导出"],["删除角色","关联用户旧 Token 是否仍可用"],["禁用用户","当前会话何时失效，其他设备如何处理"],["退出登录","当前设备失效，其他设备按需求处理"]]}/><Callout>立即生效、重新登录生效还是 Token 到期生效，必须依据需求或安全策略。需求未定义时列为待确认，不在用例中臆造“5 分钟后”。</Callout></S>
<S id="export" n="06" t="附件、导出与统计同样受权限控制" b="隐蔽泄露点"><Table title="高风险资源" headers={["资源","测试重点"]} rows={[["附件直链","替换文件 ID、复制 URL、Token 失效后访问"],["批量导出","导出范围、字段脱敏、任务下载权限"],["统计报表","数量与金额只计算授权数据"],["搜索联想","不可通过关键词探测无权记录"],["错误提示","不暴露资源是否存在、真实路径和内部标识"]]}/><Card title="用例标题示例"><p>当个人数据范围用户替换导出任务 ID 下载他人文件时，系统拒绝下载且不返回文件名、大小或临时地址。</p></Card></S>
<S id="audit" n="07" t="把运维访问也纳入授权与审计" b="统一入口与留痕"><Flow items={[["个人身份","一人一账号"],["访问审批","服务器与时段"],["代理登录","不直接暴露密码"],["操作留痕","命令与会话记录"],["高危拦截","确认或拒绝"]]}/><Card title="堡垒机解决的边界"><p>堡垒机主要治理内部运维访问：统一入口、个人身份、最小权限、会话审计和高危操作拦截。它不替代 WAF、漏洞修复或抗 DDoS，测试时要区分内部访问治理与外部攻击防护。</p></Card><Table title="访问审计测试" headers={["检查","预期"]} rows={[["未授权服务器","资产列表不可见，直连被网络策略阻断"],["授权过期","审批时段外无法建立会话"],["高危命令","按策略拦截、二次审批或完整告警"],["审计回放","能关联个人、目标、时间、输入和结果"],["账号离职","个人入口及时停用，目标密码无需散发"]]}/></S>
<S id="cases" n="08" t="用清点、结对、断言生成权限用例" b="矩阵化设计"><Flow items={[["清点入口","菜单/URL/接口/文件"],["准备身份","有权/无权/跨域"],["准备数据","本人/下级/平级/他人"],["执行断言","状态/内容/业务结果"]]}/><Card title="优先级判断"><List items={["P0/P1：越权访问、数据隔离、敏感字段与高危操作。","P1：权限变更残留、导出范围与统计泄露。","P2：低风险入口展示、多设备体验；仍按真实业务影响调整。","优先级来源于损失和暴露面，不按用例复杂度决定。"]}/></Card></S>
<S id="practice" n="09" t="为一个业务模块完成权限验收" b="练习与检查清单"><Card title="练习"><List ordered items={["列出一个业务模块的菜单、按钮、URL、接口、附件和导出入口。","准备有权、无权、同级他人和跨机构账号与数据。","画出角色 × 数据归属 × 操作矩阵。","执行水平、垂直和跨租户越权，并核对数据库结果。","修改角色和用户状态，验证当前会话与重新登录后的差异。","若项目使用堡垒机，验证审批、会话审计与高危命令策略。"]}/></Card><Check items={["四层入口全部覆盖","列表详情操作分别断言","拒绝时零内容泄露","越权操作未写入业务结果","权限生效时机有需求依据","导出统计遵守数据范围","运维访问可关联到个人"]}/></S>
</KnowledgeLayout></div>}

function Header(){return <header className="mb-10"><div className="mb-3 font-mono text-[10px] uppercase tracking-[0.22em] text-neon-cyan">Business Testing / Tutorial 07</div><h1 className="mb-3 bg-gradient-to-r from-neon-cyan to-neon-purple bg-clip-text text-3xl font-bold text-transparent md:text-4xl">权限、数据隔离与访问审计测试教程</h1><p className="text-lg leading-8 text-text-secondary">从用户页面一直测到接口、数据范围和运维入口，验证任何身份对任何资源都只能做被授权的事，并留下可追溯证据。</p></header>}
function S({id,n,t,b,children}:{id:string;n:string;t:string;b:string;children:React.ReactNode}){return <section id={id} data-knowledge-section className="mb-14"><div className="mb-5 flex items-center gap-3 border-b-2 border-space-border pb-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-neon-cyan/10 font-mono text-xs text-neon-cyan">{n}</div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold text-text-primary">{t}</h2><span className="rounded-full bg-neon-cyan/10 px-2 py-0.5 text-[10px] text-neon-cyan">{b}</span></div></div>{children}</section>}
function Card({title,children}:{title?:string;children:React.ReactNode}){return <div className="card-glow mb-4 rounded-xl p-5 text-sm leading-7 text-text-secondary">{title&&<h3 className="mb-3 text-base font-bold text-text-primary">{title}</h3>}{children}</div>}
function List({items,ordered=false}:{items:string[];ordered?:boolean}){const T=ordered?"ol":"ul";return <T className={`mt-3 space-y-2 pl-5 ${ordered?"list-decimal":"list-disc"}`}>{items.map(x=><li key={x}>{x}</li>)}</T>}
function Table({title,headers,rows}:{title:string;headers:string[];rows:string[][]}){return <Card title={title}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b border-space-border">{headers.map(x=><th key={x} className="bg-neon-cyan/5 px-4 py-3 text-left text-text-primary">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.join()} className="border-b border-space-border/50">{r.map((x,i)=><td key={x+i} className="px-4 py-2.5 text-xs leading-relaxed">{x}</td>)}</tr>)}</tbody></table></div></Card>}
function Callout({children}:{children:React.ReactNode}){return <div className="mb-4 border-l-2 border-neon-cyan bg-neon-cyan/5 px-5 py-4 text-sm leading-7 text-text-secondary">{children}</div>}
function Flow({items}:{items:string[][]}){return <Card title="访问控制链路"><div className="grid gap-3 md:grid-cols-5">{items.map((x,i)=><div key={x[0]} className={`rounded-lg border p-4 ${i===3?"border-neon-cyan/50 bg-neon-cyan/10":"border-space-border bg-space-card/50"}`}><b className="block text-xs text-text-primary">{x[0]}</b><span className="text-[11px]">{x[1]}</span></div>)}</div></Card>}
function Check({items}:{items:string[]}){return <Card title="完成检查">{items.map(x=><div key={x} className="mb-2 flex gap-2"><CheckCircle2 className="mt-1 h-4 w-4 text-neon-cyan"/>{x}</div>)}</Card>}
