export const tutorialTracks = [
  {
    slug: "foundations",
    title: "测试基础",
    eyebrow: "Foundations",
    description: "建立质量风险、测试流程、测试类型和缺陷分析的基础认知。",
    outcome: "能够独立理解需求、识别风险并完成基础测试。",
  },
  {
    slug: "business-testing",
    title: "业务与用例设计",
    eyebrow: "Business Testing",
    description: "把业务规则转化为覆盖完整、表达清楚且可以执行的测试用例。",
    outcome: "能够设计复杂业务场景、边界和异常链路。",
  },
  {
    slug: "automation",
    title: "自动化工程",
    eyebrow: "Automation",
    description: "从接口和 Web 自动化出发，建立可维护的测试代码与持续回归能力。",
    outcome: "能够搭建自动化项目并接入持续集成。",
  },
  {
    slug: "data-systems",
    title: "数据与分布式测试",
    eyebrow: "Data & Systems",
    description: "覆盖数据库、数据链路、消息队列、缓存和分布式系统质量验证。",
    outcome: "能够定位跨系统数据差异和链路故障。",
  },
  {
    slug: "quality-architecture",
    title: "质量体系与测试架构",
    eyebrow: "Quality Architecture",
    description: "从单点测试走向质量度量、测试策略、平台建设和团队质量机制。",
    outcome: "能够设计面向交付全流程的质量保障体系。",
  },
  {
    slug: "test-development",
    title: "测试开发强化支线",
    eyebrow: "SDET Track",
    description: "面向测试开发岗位，补齐编程基础、代码级测试、云原生环境、测试平台和项目作品。",
    outcome: "能够把测试能力扩展为可开发、可部署、可展示的工程实践。",
  },
  {
    slug: "ai-testing",
    title: "AI 测试工程师强化支线",
    eyebrow: "AI Quality Track",
    description: "从大模型基础出发，系统学习评估集、RAG、Agent、安全、多模态以及成本与可观测性测试。",
    outcome: "能够为概率性 AI 应用建立可评估、可回归、可审核的质量体系。",
  },
] as const;

export type TutorialTrackSlug = (typeof tutorialTracks)[number]["slug"];

export type TutorialStatus = "planned" | "published";

export type Tutorial = {
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  track: TutorialTrackSlug;
  level: "入门" | "进阶" | "专项";
  status: TutorialStatus;
  order: number;
  href?: string;
};

export const tutorials: readonly Tutorial[] = [
  {
    slug: "software-testing-foundations",
    title: "软件测试基础教程",
    subtitle: "测试基础",
    description: "从质量风险、测试流程和常见测试类型开始，建立完整的软件测试认知。",
    track: "foundations",
    level: "入门",
    status: "published",
    order: 1,
    href: "/knowledge/software-testing-foundations",
  },
  {
    slug: "test-case-design",
    title: "测试用例设计实战教程",
    subtitle: "需求到用例",
    description: "使用等价类、边界值、判定表和状态迁移，把业务需求转化为可执行用例。",
    track: "business-testing",
    level: "入门",
    status: "published",
    order: 2,
    href: "/knowledge/test-case-design",
  },
  {
    slug: "test-design-method-map",
    title: "测试设计方法地图",
    subtitle: "方法选择与进阶",
    description: "从问题类型出发，串联因果图、Pairwise、分类树、错误推测和探索性测试等进阶方法。",
    track: "business-testing",
    level: "进阶",
    status: "published",
    order: 3,
    href: "/knowledge/test-design-method-map",
  },
  {
    slug: "requirements-test-planning",
    title: "需求评审与测试方案设计教程",
    subtitle: "需求到测试计划",
    description: "从 PRD 识别漏洞、划定测试范围、评估风险，并形成可执行的测试方案和准入准出标准。",
    track: "foundations",
    level: "入门",
    status: "published",
    order: 4,
    href: "/knowledge/requirements-test-planning",
  },
  {
    slug: "defect-management-analysis",
    title: "Bug 管理与缺陷分析教程",
    subtitle: "发现到复盘",
    description: "掌握缺陷等级、有效描述、生命周期、根因分析和线上问题复盘。",
    track: "foundations",
    level: "入门",
    status: "published",
    order: 5,
    href: "/knowledge/defect-management-analysis",
  },
  {
    slug: "web-functional-testing",
    title: "Web 功能测试实战教程",
    subtitle: "页面到数据",
    description: "围绕表单、列表、搜索、权限、文件和状态流转完成一套 Web 业务测试。",
    track: "business-testing",
    level: "入门",
    status: "published",
    order: 6,
    href: "/knowledge/web-functional-testing",
  },
  {
    slug: "business-state-machine-testing",
    title: "业务状态流转测试实战教程",
    subtitle: "状态与并发",
    description: "验证订单、支付和退款的合法流转、重复提交、并发操作、回滚与补偿。",
    track: "business-testing",
    level: "进阶",
    status: "published",
    order: 7,
    href: "/knowledge/business-state-machine-testing",
  },
  {
    slug: "mobile-app-testing",
    title: "移动端 App 测试实战教程",
    subtitle: "设备与移动场景",
    description: "覆盖安装升级、权限、前后台、弱网、推送、深链和 Android/iOS 差异。",
    track: "business-testing",
    level: "进阶",
    status: "published",
    order: 8,
    href: "/knowledge/mobile-app-testing",
  },
  {
    slug: "network-packet-capture",
    title: "抓包与网络请求分析实战教程",
    subtitle: "页面到接口定位",
    description: "使用浏览器 Network、HTTP 代理和网络抓包工具，定位请求参数、响应与耗时问题。",
    track: "business-testing",
    level: "入门",
    status: "published",
    order: 9,
    href: "/knowledge/network-packet-capture",
  },
  {
    slug: "sql-database-testing",
    title: "SQL 与数据库测试教程",
    subtitle: "查询到对账",
    description: "从测试数据准备、SQL 查询，到业务数据核对、差异定位和自动化校验。",
    track: "data-systems",
    level: "进阶",
    status: "published",
    order: 10,
    href: "/knowledge/sql-database-testing",
  },
  {
    slug: "python-pytest-testing",
    title: "Python 与 pytest 测试开发教程",
    subtitle: "从代码到测试项目",
    description: "学习 Python 测试基础、fixture、参数化、数据驱动、日志报告和项目结构。",
    track: "automation",
    level: "入门",
    status: "published",
    order: 11,
    href: "/knowledge/python-pytest-testing",
  },
  {
    slug: "api-test-automation",
    title: "接口自动化测试教程",
    subtitle: "pytest + CI",
    description: "完成请求封装、数据驱动、分层断言、测试报告和持续集成的完整项目。",
    track: "automation",
    level: "进阶",
    status: "published",
    order: 12,
    href: "/knowledge/api-test-automation",
  },
  {
    slug: "mock-test-doubles",
    title: "Mock 与测试桩实战教程",
    subtitle: "隔离外部依赖",
    description: "围绕库存、优惠和支付依赖，掌握函数桩、HTTP 测试桩、浏览器拦截与契约校验。",
    track: "automation",
    level: "进阶",
    status: "published",
    order: 13,
    href: "/knowledge/mock-test-doubles",
  },
  {
    slug: "playwright-test-automation",
    title: "Playwright 自动化测试教程",
    subtitle: "Web E2E",
    description: "围绕真实业务流程，学习稳定定位、页面对象、测试数据和失败诊断。",
    track: "automation",
    level: "进阶",
    status: "published",
    order: 14,
    href: "/knowledge/playwright-test-automation",
  },
  {
    slug: "continuous-testing-cicd",
    title: "持续测试与 CI/CD 工程教程",
    subtitle: "测试进入流水线",
    description: "建立 PR 检查、分层回归、失败归因、Flaky 治理、报告归档和发布阻断机制。",
    track: "automation",
    level: "进阶",
    status: "published",
    order: 15,
    href: "/knowledge/continuous-testing-cicd",
  },
  {
    slug: "microservices-testing",
    title: "微服务测试实战教程",
    subtitle: "服务协作与故障",
    description: "验证网关认证、服务调用、超时重试、熔断降级、分布式事务和链路追踪。",
    track: "data-systems",
    level: "进阶",
    status: "published",
    order: 16,
    href: "/knowledge/microservices-testing",
  },
  {
    slug: "message-queue-testing",
    title: "消息队列与异步任务测试教程",
    subtitle: "异步与最终一致",
    description: "覆盖消息重复、丢失、乱序、重试、死信、积压和最终一致性验证。",
    track: "data-systems",
    level: "进阶",
    status: "published",
    order: 17,
    href: "/knowledge/message-queue-testing",
  },
  {
    slug: "cache-testing",
    title: "缓存测试实战教程",
    subtitle: "Redis 与一致性",
    description: "验证缓存穿透、击穿、雪崩、热 Key、大 Key、更新失效和故障降级。",
    track: "data-systems",
    level: "进阶",
    status: "published",
    order: 18,
    href: "/knowledge/cache-testing",
  },
  {
    slug: "resilience-disaster-recovery-testing",
    title: "稳定性、容灾与故障演练教程",
    subtitle: "故障到恢复",
    description: "演练服务宕机、网络异常、主从切换、第三方失败、限流降级和备份恢复。",
    track: "data-systems",
    level: "专项",
    status: "published",
    order: 19,
    href: "/knowledge/resilience-disaster-recovery-testing",
  },
  {
    slug: "test-strategy-quality-gates",
    title: "测试策略与质量门禁教程",
    subtitle: "风险到发布",
    description: "围绕真实版本制定风险驱动测试策略，建立分层验证、质量门禁、发布准入和线上质量闭环。",
    track: "quality-architecture",
    level: "进阶",
    status: "published",
    order: 20,
    href: "/knowledge/test-strategy-quality-gates",
  },
  {
    slug: "observability-testing",
    title: "日志、监控与可观测性测试教程",
    subtitle: "线上质量证据链",
    description: "验证日志、Metrics、Trace、告警和 SLI/SLO/SLA，建立线上问题证据链。",
    track: "quality-architecture",
    level: "进阶",
    status: "published",
    order: 21,
    href: "/knowledge/observability-testing",
  },
  {
    slug: "test-metrics-quality-review",
    title: "测试报告、效能度量与质量复盘教程",
    subtitle: "从数据到改进",
    description: "使用覆盖、缺陷、有效性、自动化收益和线上问题数据推动质量改进。",
    track: "quality-architecture",
    level: "进阶",
    status: "published",
    order: 22,
    href: "/knowledge/test-metrics-quality-review",
  },
  {
    slug: "test-development-programming",
    title: "测试开发编程基础教程",
    subtitle: "数据结构、算法与代码质量",
    description: "补齐测试开发岗位常见的编程基本功，建立代码阅读、问题拆解和工程质量意识。",
    track: "test-development",
    level: "进阶",
    status: "planned",
    order: 22.1,
  },
  {
    slug: "unit-component-integration-testing",
    title: "单元、组件与集成测试实战教程",
    subtitle: "从代码内部验证质量",
    description: "覆盖单元、组件和集成测试的职责边界、依赖隔离、测试容器与覆盖率使用。",
    track: "test-development",
    level: "进阶",
    status: "planned",
    order: 22.2,
  },
  {
    slug: "docker-kubernetes-testing",
    title: "Docker 与 Kubernetes 测试环境实战教程",
    subtitle: "容器化测试环境",
    description: "学习容器、网络、日志、配置和临时环境，建立可重复部署与排障的测试环境。",
    track: "test-development",
    level: "进阶",
    status: "planned",
    order: 22.3,
  },
  {
    slug: "test-platform-development",
    title: "测试平台开发实战教程",
    subtitle: "从框架到平台",
    description: "围绕任务调度、环境管理、报告存储、权限和通知，完成可持续维护的测试平台。",
    track: "test-development",
    level: "专项",
    status: "planned",
    order: 22.4,
  },
  {
    slug: "testing-portfolio-interview",
    title: "测试工程师项目作品集与面试指南",
    subtitle: "把能力转化为求职证据",
    description: "整理自动化项目、测试方案、质量指标和问题复盘，形成能够讲清设计取舍的作品集。",
    track: "test-development",
    level: "专项",
    status: "planned",
    order: 22.5,
  },
  {
    slug: "llm-foundations-testing",
    title: "大模型基础与测试思维教程",
    subtitle: "理解概率输出",
    description: "理解 Token、上下文、采样参数、提示词和模型边界，建立不同于确定性系统的测试思维。",
    track: "ai-testing",
    level: "入门",
    status: "planned",
    order: 22.6,
  },
  {
    slug: "ai-application-testing-system",
    title: "AI 应用测试体系教程",
    subtitle: "概率输出评估",
    description: "建立评估集、人工金标、机器 Check、人工审核置信度和 AI 回归测试闭环。",
    track: "ai-testing",
    level: "专项",
    status: "published",
    order: 23,
    href: "/knowledge/ai-application-testing-system",
  },
  {
    slug: "rag-knowledge-base-testing",
    title: "RAG 知识库测试实战教程",
    subtitle: "从解析到回答",
    description: "验证文档解析、切分、召回、重排、引用、幻觉、权限隔离和知识更新。",
    track: "ai-testing",
    level: "专项",
    status: "planned",
    order: 23.1,
  },
  {
    slug: "ai-agent-testing",
    title: "AI Agent 测试实战教程",
    subtitle: "工具调用与任务轨迹",
    description: "验证工具选择、参数、多步骤任务、重试终止、权限副作用和人工接管。",
    track: "ai-testing",
    level: "专项",
    status: "planned",
    order: 23.2,
  },
  {
    slug: "llm-security-red-teaming",
    title: "大模型安全与红队测试教程",
    subtitle: "提示词攻击与安全边界",
    description: "覆盖提示词注入、越狱、敏感信息泄露、工具滥用、内容安全和权限绕过。",
    track: "ai-testing",
    level: "专项",
    status: "planned",
    order: 23.3,
  },
  {
    slug: "multimodal-ocr-testing",
    title: "多模态、OCR 与文档智能测试教程",
    subtitle: "图像与结构化数据质量",
    description: "验证图片、表格、印章、遮挡文档以及金额日期等关键字段的识别与入库质量。",
    track: "ai-testing",
    level: "专项",
    status: "planned",
    order: 23.4,
  },
  {
    slug: "ai-performance-cost-observability",
    title: "AI 应用性能、成本与可观测性教程",
    subtitle: "延迟、Token 与线上质量",
    description: "建立首字延迟、生成速度、Token 成本、失败率、模型漂移和线上反馈监控。",
    track: "ai-testing",
    level: "进阶",
    status: "planned",
    order: 23.5,
  },
  {
    slug: "prompt-context-engineering-for-testing",
    title: "AI 时代测试提示词与上下文工程教程",
    subtitle: "让 AI 稳定理解测试任务",
    description: "学习任务拆解、上下文组织、结构化输出、Few-shot 示例和提示词回归，提高测试分析与用例生成质量。",
    track: "ai-testing",
    level: "进阶",
    status: "planned",
    order: 23.6,
  },
  {
    slug: "testing-skills-design",
    title: "测试 Skill 设计与资产封装教程",
    subtitle: "把测试经验变成可复用能力",
    description: "把测试规范、检查清单、脚本和领域经验封装为可复用 Skill，并验证输入、输出和执行边界。",
    track: "ai-testing",
    level: "进阶",
    status: "planned",
    order: 23.7,
  },
  {
    slug: "mcp-testing-integration",
    title: "MCP 工具接入与安全测试教程",
    subtitle: "连接数据、工具与测试系统",
    description: "学习 MCP 工具发现、参数校验、权限控制、异常处理、敏感数据保护和工具调用测试。",
    track: "ai-testing",
    level: "专项",
    status: "planned",
    order: 23.8,
  },
  {
    slug: "ai-testing-workflow-orchestration",
    title: "AI 测试工作流编排与人机协作教程",
    subtitle: "从单次对话到稳定流程",
    description: "编排需求分析、用例生成、脚本校验、执行、报告和人工审核，建立可追踪、可恢复的测试提效流程。",
    track: "ai-testing",
    level: "专项",
    status: "planned",
    order: 23.9,
  },
];

export function getTutorialTrack(slug: string) {
  return tutorialTracks.find((track) => track.slug === slug);
}

export function getTutorialsByTrack(track: TutorialTrackSlug) {
  return tutorials.filter((tutorial) => tutorial.track === track).sort((a, b) => a.order - b.order);
}
