export const tutorialTracks = [
  {
    slug: "foundations",
    title: "测试基础",
    eyebrow: "Foundations",
    description: "建立质量风险、测试流程、测试类型和缺陷分析的基础认知。",
    outcome: "能够独立理解需求、识别风险并完成基础测试。",
  },
  {
    slug: "business-testing",
    title: "业务与用例设计",
    eyebrow: "Business Testing",
    description: "把业务规则转化为覆盖完整、表达清楚且可以执行的测试用例，并验证角色、数据与访问边界。",
    outcome: "能够设计复杂业务场景、边界、异常链路与权限矩阵。",
  },
  {
    slug: "automation",
    title: "自动化工程",
    eyebrow: "Automation",
    description: "从接口和 Web 自动化出发，建立可维护的测试代码与持续回归能力。",
    outcome: "能够搭建自动化项目并接入持续集成。",
  },
  {
    slug: "data-systems",
    title: "数据与分布式测试",
    eyebrow: "Data & Systems",
    description: "覆盖测试数据治理、数据库、数据链路、消息队列、缓存和分布式系统质量验证。",
    outcome: "能够准备可信测试数据，并定位跨系统数据差异和链路故障。",
  },
  {
    slug: "quality-architecture",
    title: "质量体系与测试架构",
    eyebrow: "Quality Architecture",
    description: "从单点测试走向质量度量、测试策略、资产追溯和团队质量机制。",
    outcome: "能够设计可追溯、可校验、可复用的全流程质量保障体系。",
  },
  {
    slug: "test-development",
    title: "测试开发强化支线",
    eyebrow: "SDET Track",
    description: "面向测试开发岗位，补齐编程基础、代码级测试、云原生环境、测试平台和项目作品。",
    outcome: "能够把测试能力扩展为可开发、可部署、可展示的工程实践。",
  },
  {
    slug: "ai-testing",
    title: "AI 测试工程师强化支线",
    eyebrow: "AI Quality Track",
    description: "先学习如何用 AI 生产可信测试资产，再学习如何评估大模型、OCR、RAG、Agent、安全与线上质量。",
    outcome: "既能用 AI 提升测试生产效率，也能为概率性 AI 应用建立可评估、可回归、可审核的质量体系。",
  },
] as const;

export type TutorialTrackSlug = (typeof tutorialTracks)[number]["slug"];

export type TutorialStatus = "planned" | "published";

export type Tutorial = {
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  track: TutorialTrackSlug;
  level: "入门" | "进阶" | "专项";
  status: TutorialStatus;
  order: number;
  href?: string;
  phase?: string;
  phaseStep?: number;
};

export const tutorials: readonly Tutorial[] = [
  {
    slug: "software-testing-foundations",
    title: "软件测试基础教程",
    subtitle: "测试基础",
    description: "从质量风险、测试流程和常见测试类型开始，建立完整的软件测试认知。",
    track: "foundations",
    level: "入门",
    status: "published",
    order: 1,
    href: "/knowledge/software-testing-foundations",
  },
  {
    slug: "test-case-design",
    title: "测试用例设计实战教程",
    subtitle: "需求到用例",
    description: "使用等价类、边界值、判定表和状态迁移，把业务需求转化为可执行用例。",
    track: "business-testing",
    level: "入门",
    status: "published",
    order: 2,
    href: "/knowledge/test-case-design",
  },
  {
    slug: "test-design-method-map",
    title: "测试设计方法地图",
    subtitle: "方法选择与进阶",
    description: "从问题类型出发，串联因果图、Pairwise、分类树、错误推测和探索性测试等进阶方法。",
    track: "business-testing",
    level: "进阶",
    status: "published",
    order: 3,
    href: "/knowledge/test-design-method-map",
  },
  {
    slug: "requirements-test-planning",
    title: "需求评审与测试方案设计教程",
    subtitle: "需求到测试计划",
    description: "从 PRD 识别漏洞、划定测试范围、评估风险，并形成可执行的测试方案和准入准出标准。",
    track: "foundations",
    level: "入门",
    status: "published",
    order: 4,
    href: "/knowledge/requirements-test-planning",
  },
  {
    slug: "defect-management-analysis",
    title: "Bug 管理与缺陷分析教程",
    subtitle: "发现到复盘",
    description: "掌握缺陷等级、有效描述、生命周期、根因分析和线上问题复盘。",
    track: "foundations",
    level: "入门",
    status: "published",
    order: 5,
    href: "/knowledge/defect-management-analysis",
  },
  {
    slug: "web-functional-testing",
    title: "Web 功能测试实战教程",
    subtitle: "页面到数据",
    description: "围绕表单、列表、搜索、权限、文件和状态流转完成一套 Web 业务测试。",
    track: "business-testing",
    level: "入门",
    status: "published",
    order: 6,
    href: "/knowledge/web-functional-testing",
  },
  {
    slug: "access-control-testing",
    title: "权限、数据隔离与访问审计测试教程",
    subtitle: "角色、数据与操作留痕",
    description: "从菜单、按钮、URL、接口和数据范围验证权限，并覆盖越权、会话残留与运维访问审计。",
    track: "business-testing",
    level: "进阶",
    status: "published",
    order: 6.5,
    href: "/knowledge/access-control-testing",
  },
  {
    slug: "business-state-machine-testing",
    title: "业务状态流转测试实战教程",
    subtitle: "状态与并发",
    description: "验证订单、支付和退款的合法流转、重复提交、并发操作、回滚与补偿。",
    track: "business-testing",
    level: "进阶",
    status: "published",
    order: 7,
    href: "/knowledge/business-state-machine-testing",
  },
  {
    slug: "mobile-app-testing",
    title: "移动端 App 测试实战教程",
    subtitle: "设备与移动场景",
    description: "覆盖安装升级、权限、前后台、弱网、推送、深链和 Android/iOS 差异。",
    track: "business-testing",
    level: "进阶",
    status: "published",
    order: 8,
    href: "/knowledge/mobile-app-testing",
  },
  {
    slug: "network-packet-capture",
    title: "抓包与网络请求分析实战教程",
    subtitle: "页面到接口定位",
    description: "使用浏览器 Network、HTTP 代理和网络抓包工具，定位请求参数、响应与耗时问题。",
    track: "business-testing",
    level: "入门",
    status: "published",
    order: 9,
    href: "/knowledge/network-packet-capture",
  },
  {
    slug: "sql-database-testing",
    title: "SQL 与数据库测试教程",
    subtitle: "查询到对账",
    description: "从测试数据准备、SQL 查询，到业务数据核对、差异定位和自动化校验。",
    track: "data-systems",
    level: "进阶",
    status: "published",
    order: 10,
    href: "/knowledge/sql-database-testing",
  },
  {
    slug: "test-data-management",
    title: "测试数据设计与环境治理教程",
    subtitle: "造数、隔离、清理与对账",
    description: "把测试数据作为工程资产管理，覆盖造数方式、环境隔离、脱敏、清理、漂移巡检和跨层一致性。",
    track: "data-systems",
    level: "进阶",
    status: "published",
    order: 10.5,
    href: "/knowledge/test-data-management",
  },
  {
    slug: "python-pytest-testing",
    title: "Python 与 pytest 测试开发教程",
    subtitle: "从代码到测试项目",
    description: "学习 Python 测试基础、fixture、参数化、数据驱动、日志报告和项目结构。",
    track: "automation",
    level: "入门",
    status: "published",
    order: 11,
    href: "/knowledge/python-pytest-testing",
  },
  {
    slug: "api-test-automation",
    title: "接口自动化测试教程",
    subtitle: "pytest + CI",
    description: "完成请求封装、数据驱动、分层断言、测试报告和持续集成的完整项目。",
    track: "automation",
    level: "进阶",
    status: "published",
    order: 12,
    href: "/knowledge/api-test-automation",
  },
  {
    slug: "mock-test-doubles",
    title: "Mock 与测试桩实战教程",
    subtitle: "隔离外部依赖",
    description: "围绕库存、优惠和支付依赖，掌握函数桩、HTTP 测试桩、浏览器拦截与契约校验。",
    track: "automation",
    level: "进阶",
    status: "published",
    order: 13,
    href: "/knowledge/mock-test-doubles",
  },
  {
    slug: "playwright-test-automation",
    title: "Playwright 自动化测试教程",
    subtitle: "Web E2E",
    description: "围绕真实业务流程，学习稳定定位、页面对象、测试数据和失败诊断。",
    track: "automation",
    level: "进阶",
    status: "published",
    order: 14,
    href: "/knowledge/playwright-test-automation",
  },
  {
    slug: "continuous-testing-cicd",
    title: "持续测试与 CI/CD 工程教程",
    subtitle: "测试进入流水线",
    description: "建立 PR 检查、分层回归、失败归因、Flaky 治理、报告归档和发布阻断机制。",
    track: "automation",
    level: "进阶",
    status: "published",
    order: 15,
    href: "/knowledge/continuous-testing-cicd",
  },
  {
    slug: "microservices-testing",
    title: "微服务测试实战教程",
    subtitle: "服务协作与故障",
    description: "验证网关认证、服务调用、超时重试、熔断降级、分布式事务和链路追踪。",
    track: "data-systems",
    level: "进阶",
    status: "published",
    order: 16,
    href: "/knowledge/microservices-testing",
  },
  {
    slug: "message-queue-testing",
    title: "消息队列与异步任务测试教程",
    subtitle: "异步与最终一致",
    description: "覆盖消息重复、丢失、乱序、重试、死信、积压和最终一致性验证。",
    track: "data-systems",
    level: "进阶",
    status: "published",
    order: 17,
    href: "/knowledge/message-queue-testing",
  },
  {
    slug: "cache-testing",
    title: "缓存测试实战教程",
    subtitle: "Redis 与一致性",
    description: "验证缓存穿透、击穿、雪崩、热 Key、大 Key、更新失效和故障降级。",
    track: "data-systems",
    level: "进阶",
    status: "published",
    order: 18,
    href: "/knowledge/cache-testing",
  },
  {
    slug: "resilience-disaster-recovery-testing",
    title: "稳定性、容灾与故障演练教程",
    subtitle: "故障到恢复",
    description: "演练服务宕机、网络异常、主从切换、第三方失败、限流降级和备份恢复。",
    track: "data-systems",
    level: "专项",
    status: "published",
    order: 19,
    href: "/knowledge/resilience-disaster-recovery-testing",
  },
  {
    slug: "test-strategy-quality-gates",
    title: "测试策略与质量门禁教程",
    subtitle: "风险到发布",
    description: "围绕真实版本制定风险驱动测试策略，建立分层验证、质量门禁、发布准入和线上质量闭环。",
    track: "quality-architecture",
    level: "进阶",
    status: "published",
    order: 20,
    href: "/knowledge/test-strategy-quality-gates",
  },
  {
    slug: "observability-testing",
    title: "日志、监控与可观测性测试教程",
    subtitle: "线上质量证据链",
    description: "验证日志、Metrics、Trace、告警和 SLI/SLO/SLA，建立线上问题证据链。",
    track: "quality-architecture",
    level: "进阶",
    status: "published",
    order: 21,
    href: "/knowledge/observability-testing",
  },
  {
    slug: "test-metrics-quality-review",
    title: "测试报告、效能度量与质量复盘教程",
    subtitle: "从数据到改进",
    description: "使用覆盖、缺陷、有效性、自动化收益和线上问题数据推动质量改进。",
    track: "quality-architecture",
    level: "进阶",
    status: "published",
    order: 22,
    href: "/knowledge/test-metrics-quality-review",
  },
  {
    slug: "test-assets-traceability",
    title: "测试资产工程与版本追溯教程",
    subtitle: "规则、风险、用例与交付闭环",
    description: "把测试点、风险、用例、缺陷模式、评审和版本总结连接成可追溯、可校验、可复用的测试资产体系。",
    track: "quality-architecture",
    level: "进阶",
    status: "published",
    order: 22.01,
    href: "/knowledge/test-assets-traceability",
  },
  {
    slug: "test-development-programming",
    title: "测试开发编程基础教程",
    subtitle: "数据结构、算法与代码质量",
    description: "补齐测试开发岗位常见的编程基本功，建立代码阅读、问题拆解和工程质量意识。",
    track: "test-development",
    level: "进阶",
    status: "planned",
    order: 22.1,
  },
  {
    slug: "unit-component-integration-testing",
    title: "单元、组件与集成测试实战教程",
    subtitle: "从代码内部验证质量",
    description: "覆盖单元、组件和集成测试的职责边界、依赖隔离、测试容器与覆盖率使用。",
    track: "test-development",
    level: "进阶",
    status: "planned",
    order: 22.2,
  },
  {
    slug: "docker-kubernetes-testing",
    title: "Docker 与 Kubernetes 测试环境实战教程",
    subtitle: "容器化测试环境",
    description: "学习容器、网络、日志、配置和临时环境，建立可重复部署与排障的测试环境。",
    track: "test-development",
    level: "进阶",
    status: "planned",
    order: 22.3,
  },
  {
    slug: "test-platform-development",
    title: "测试资产平台与规则引擎开发教程",
    subtitle: "从文件到可治理平台",
    description: "围绕文档解析、用例存储、版本追溯、规则校验、人工评审和报告数据，完成可持续维护的测试资产平台。",
    track: "test-development",
    level: "专项",
    status: "published",
    order: 22.4,
    href: "/knowledge/test-platform-development",
  },
  {
    slug: "testing-portfolio-interview",
    title: "测试工程师项目作品集与面试指南",
    subtitle: "把能力转化为求职证据",
    description: "整理自动化项目、测试方案、质量指标和问题复盘，形成能够讲清设计取舍的作品集。",
    track: "test-development",
    level: "专项",
    status: "planned",
    order: 22.5,
  },
  {
    slug: "llm-foundations-testing",
    title: "大模型基础与测试思维教程",
    subtitle: "概率输出、边界与可复现性",
    description: "理解 Token、上下文、采样、模型组合边界和非确定性失败，建立适用于 AI 系统的测试断言与实验记录方法。",
    track: "ai-testing",
    level: "入门",
    status: "published",
    order: 22.9,
    href: "/knowledge/llm-foundations-testing",
    phase: "测试 AI 系统",
    phaseStep: 1,
  },
  {
    slug: "traditional-automation-to-ai-testing",
    title: "从传统自动化到 AI 辅助测试迁移指南",
    subtitle: "复用 pytest 与 Playwright 资产",
    description: "盘点现有脚本、夹具、Page Object、断言和报告，把确定性自动化逐步封装为 Agent 可安全调用的测试能力。",
    track: "ai-testing",
    level: "进阶",
    status: "published",
    order: 22.51,
    href: "/knowledge/traditional-automation-to-ai-testing",
    phase: "用 AI 做测试",
    phaseStep: 1,
  },
  {
    slug: "ai-testing-workflow-orchestration",
    title: "AI 测试资产生产与人机审核教程",
    subtitle: "从可靠输入到可信资产",
    description: "整合系统 Prompt、上下文证据、任务拆解、候选用例、机器校验、人工审核和版本回归，跑通可追踪的测试资产生产流程。",
    track: "ai-testing",
    level: "专项",
    status: "published",
    order: 22.7,
    phase: "用 AI 做测试",
    href: "/knowledge/ai-testing-workflow-orchestration",
    phaseStep: 2,
  },
  {
    slug: "testing-skills-design",
    title: "测试 Skill 与知识资产封装教程",
    subtitle: "把经验封装成可复用能力",
    description: "把规范、风险规则、缺陷模式、脚本和领域经验封装成可组合 Skill，并用历史样本验证边界与稳定性。",
    track: "ai-testing",
    level: "进阶",
    status: "published",
    order: 22.8,
    phase: "用 AI 做测试",
    href: "/knowledge/testing-skills-design",
    phaseStep: 3,
  },
  {
    slug: "ai-application-testing-system",
    title: "AI 应用评估体系教程",
    subtitle: "评估集、金标与版本回归",
    description: "建立分层评估集、人工金标、多维评分、机器 Check、人工评审路由和可复现的 AI 回归体系。",
    track: "ai-testing",
    level: "专项",
    status: "published",
    order: 23,
    href: "/knowledge/ai-application-testing-system",
    phase: "测试 AI 系统",
    phaseStep: 2,
  },
  {
    slug: "rag-knowledge-base-testing",
    title: "RAG 知识库测试实战教程",
    subtitle: "从解析到回答",
    description: "验证文档解析、切分、召回、重排、引用、幻觉、权限隔离和知识更新。",
    track: "ai-testing",
    level: "专项",
    status: "published",
    order: 23.2,
    href: "/knowledge/rag-knowledge-base-testing",
    phase: "测试 AI 系统",
    phaseStep: 4,
  },
  {
    slug: "ai-agent-testing",
    title: "AI Agent 与 MCP 工具测试实战教程",
    subtitle: "任务轨迹、工具协议与副作用",
    description: "验证多轮规划、MCP 能力发现、工具选择与参数、鉴权权限、重试幂等、人工审批和安全回退。",
    track: "ai-testing",
    level: "专项",
    status: "published",
    order: 23.3,
    href: "/knowledge/ai-agent-testing",
    phase: "测试 AI 系统",
    phaseStep: 5,
  },
  {
    slug: "llm-security-red-teaming",
    title: "大模型安全与红队测试教程",
    subtitle: "提示词攻击与安全边界",
    description: "覆盖提示词注入、越狱、敏感信息泄露、工具滥用、内容安全和权限绕过。",
    track: "ai-testing",
    level: "专项",
    status: "published",
    order: 23.4,
    href: "/knowledge/llm-security-red-teaming",
    phase: "测试 AI 系统",
    phaseStep: 6,
  },
  {
    slug: "multimodal-ocr-testing",
    title: "多模态、OCR 与文档智能测试教程",
    subtitle: "图像与结构化数据质量",
    description: "验证图片、表格、印章、遮挡文档以及金额日期等关键字段的识别与入库质量。",
    track: "ai-testing",
    level: "专项",
    status: "published",
    order: 23.1,
    phase: "测试 AI 系统",
    href: "/knowledge/multimodal-ocr-testing",
    phaseStep: 3,
  },
  {
    slug: "ai-performance-cost-observability",
    title: "AI 应用性能、成本与可观测性教程",
    subtitle: "延迟、Token 与线上质量",
    description: "建立首字延迟、生成速度、Token 成本、失败率、模型漂移和线上反馈监控。",
    track: "ai-testing",
    level: "进阶",
    status: "published",
    order: 23.5,
    href: "/knowledge/ai-performance-cost-observability",
    phase: "测试 AI 系统",
    phaseStep: 7,
  },
];

export const aiTestingCaseStudies = [
  {
    title: "AI 生成测试用例人工审核实战",
    subtitle: "100 条候选案例拆解",
    description: "用 100 条真实结构的候选账本，查看错误分类、机器 Check、人工裁决和回流机制如何落地。",
    href: "/blog/ai-generated-test-cases-human-review",
  },
] as const;

export const aiAssistedTestingTutorials = tutorials
  .filter((tutorial) => tutorial.phase === "用 AI 做测试")
  .sort((a, b) => (a.phaseStep ?? 0) - (b.phaseStep ?? 0));

export const aiSystemQualityTutorials = tutorials
  .filter((tutorial) => tutorial.phase === "测试 AI 系统")
  .sort((a, b) => (a.phaseStep ?? 0) - (b.phaseStep ?? 0));

export function getTutorialTrack(slug: string) {
  return tutorialTracks.find((track) => track.slug === slug);
}

export function getTutorialsByTrack(track: TutorialTrackSlug) {
  return tutorials.filter((tutorial) => tutorial.track === track).sort((a, b) => a.order - b.order);
}
