import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import { KnowledgeLayout, type SectionItem } from "@/components/KnowledgeLayout";
import { buildPageMetadata } from "@/lib/site";

export const metadata = buildPageMetadata({ title: "稳定性、容灾与故障演练教程", description: "围绕商城下单、支付与退款链路，学习服务宕机、网络延迟丢包、数据库切换、第三方失败、限流降级以及备份恢复演练。", path: "/knowledge/resilience-disaster-recovery-testing", tags: ["稳定性测试", "容灾", "故障注入", "备份恢复"] });
const sections: SectionItem[] = [{id:"goal",label:"演练目标"},{id:"plan",label:"演练计划"},{id:"service",label:"服务宕机"},{id:"network",label:"延迟与丢包"},{id:"database",label:"主从切换"},{id:"third-party",label:"第三方失败"},{id:"degrade",label:"限流与降级"},{id:"backup",label:"备份恢复"},{id:"practice",label:"练习与清单"}];
const matrix = [["订单服务宕机","新订单无法创建","摘除实例；健康实例承接；不产生半单"],["网络延迟与丢包","超时、重复提交、重试风暴","超时预算有效；幂等；重试有上限"],["数据库主从切换","短暂写失败或读旧数据","恢复在 RTO 内；无事务丢失"],["支付渠道失败","已扣款但订单未确认","对账与补偿可追踪，不重复扣款"],["对象存储不可用","凭证上传失败","核心交易不被非核心附件拖垮"]];

export default function ResiliencePage(){return <div className="mx-auto max-w-5xl animate-fade-in"><Link href="/knowledge/tutorials?track=distributed-data" className="mb-8 inline-flex items-center gap-2 text-sm text-text-secondary hover:text-neon-cyan"><ArrowLeft className="h-4 w-4"/>返回分布式系统与数据链路模块</Link><KnowledgeLayout sections={sections} searchPlaceholder="搜索容灾与故障演练关键词...">
<header className="mb-10"><div className="mb-3 font-mono text-[10px] uppercase tracking-[0.22em] text-neon-cyan">Distributed Quality / Tutorial 19</div><h1 className="mb-3 bg-gradient-to-r from-neon-cyan to-neon-purple bg-clip-text text-3xl font-bold text-transparent md:text-4xl">稳定性、容灾与故障演练教程</h1><p className="mb-6 text-lg leading-8 text-text-secondary">从缓存局部故障继续扩大范围，证明商城在服务、网络、数据库和第三方异常下能够止损、恢复并保持资金数据正确。</p><div className="flex flex-wrap gap-6 text-sm text-text-secondary"><span>9 个章节</span><span>故障注入 + 恢复验证</span><span>RTO / RPO / 证据链</span></div></header>
<S id="goal" n="01" t="先定义稳定性，而不是盲目拔服务" b="业务结果优先"><Flow title="一次完整演练闭环" items={[["稳态基线","成功率与延迟"],["注入故障","单一、可撤销"],["观察响应","检测、隔离、降级"],["撤销恢复","数据对账与复盘"]]}/><Table title="商城故障矩阵" headers={["故障","业务风险","通过标准"]} rows={matrix}/><Callout>稳定性不是“永不失败”，而是故障发生时影响范围可控、核心业务有明确退路、数据不被破坏，并能在承诺时间内恢复。</Callout></S>
<S id="plan" n="02" t="把演练写成可停止的实验" b="先准备再注入"><div className="grid gap-4 md:grid-cols-2"><Card title="演练前"><List items={["限定隔离测试环境、服务、流量和持续时间。","确定稳态指标：下单成功率、重复扣款数、P99、消息积压。","写明假设、注入方式、负责人和观察人。","设置停止条件、回滚操作和数据清理方式。"]}/></Card><Card title="演练后"><List items={["先撤销故障并确认资源恢复。","对账订单、库存、支付和退款。","保存指标、日志、Trace 与操作时间线。","把暴露的问题转成缺陷、告警或自动化用例。"]}/></Card></div><Code title="实验卡示意">{`hypothesis: 订单服务损失 1 个实例时，下单成功率仍 >= 99.5%
scope: staging / 10% test traffic / 10 minutes
abort: error_rate > 5% for 60s OR duplicate_payment > 0
recovery: remove fault -> wait healthy -> reconcile orders`}</Code></S>
<S id="service" n="03" t="演练服务宕机与实例摘除" b="无半单、可接管"><Card title="用例：当一个订单实例突然宕机时，健康实例应接管请求"><List ordered items={["预热固定测试流量并记录实例分布。","只终止一个测试实例，保持其余依赖不变。","观察健康检查、负载均衡摘除时间和错误率。","对超时请求使用同一幂等键重试。","核对订单、库存预占和支付单，确认没有重复或半成品。","恢复实例，确认不会一次性消费过期任务造成尖峰。"]}/></Card><Timeline items={[["检测","健康检查识别异常"],["隔离","流量停止进入坏实例"],["接管","健康实例处理新请求"],["恢复","补偿并回到稳态"]]}/></S>
<S id="network" n="04" t="注入网络延迟、抖动与丢包" b="验证超时预算"><Table title="网络故障用例" headers={["用例标题","注入","断言"]} rows={[["当库存接口延迟 800ms 时，订单服务应在预算内失败或降级","延迟 + 抖动","超时边界明确，不无限等待"],["当支付回调响应丢失时，渠道重试不应重复扣款","响应丢包","同一回调幂等，订单最终一致"],["当消息链路间歇丢包时，事件应重试并可追踪","10% 丢包","无静默丢失，超限进入死信并告警"]]}/><Code title="Toxiproxy 示例（隔离环境）">{`toxiproxy-cli toxic add inventory \
  --type latency --attribute latency=800 --attribute jitter=100
toxiproxy-cli toxic remove inventory -n latency_downstream`}</Code><Callout>超时、重试和熔断要作为组合测试。单看重试成功率，可能掩盖重试风暴对下游造成的二次伤害。</Callout></S>
<S id="database" n="05" t="验证数据库主从切换" b="事务与时间窗口"><Card title="先定义两个目标"><List items={["RTO：从数据库不可用到商城恢复可接受服务的最长时间。","RPO：切换后允许丢失的数据时间窗口；订单与支付通常要求接近零。"]}/></Card><Card title="用例：当主库失效并切换到新主库时，已确认订单不应丢失"><List ordered items={["持续创建带 run_id 的订单并记录提交时间。","在授权的测试集群触发主库故障。","观察连接重建、写入失败和只读窗口。","恢复后按订单号对账数据库、库存和支付流水。","检查旧主库回归时不会产生双主写入。"]}/></Card><Table title="切换验收" headers={["检查点","证据"]} rows={[["可用性","错误开始与恢复时间，计算实际 RTO"],["数据完整性","切换前后业务键连续，无已确认事务丢失"],["一致性","读写分离不会长期读到旧订单状态"],["运维动作","告警、切换、回切和负责人时间线完整"]]}/></S>
<S id="third-party" n="06" t="控制第三方支付与物流失败" b="不能控制依赖也能测试"><Flow title="支付未知结果的处理" items={[["支付请求","携带幂等键"],["渠道超时","结果未知"],["主动查询","按流水号确认"],["补偿对账","更新订单或退款"]]}/><Card title="用例：当支付渠道超时但实际扣款成功时，系统应通过查询或对账确认结果"><List items={["使用可编程 Stub 返回超时，同时写入“渠道成功”状态。","禁止客户端无新幂等键重复发起支付。","验证查询、回调或对账任务把订单推进到 PAID。","若超过业务期限，验证自动退款且退款只发生一次。","报告必须关联 orderNo、paymentNo、channelNo 与 traceId。"]}/></Card></S>
<S id="degrade" n="07" t="验证限流、熔断、降级与恢复" b="保护核心交易"><Table title="分级保护策略" headers={["能力","商城例子","测试重点"]} rows={[["限流","活动入口限制瞬时请求","返回可识别状态；不误伤支付回调"],["熔断","库存依赖持续失败后快速失败","阈值、半开探测、恢复正确"],["降级","暂时关闭推荐与评价","核心下单仍可用；页面明确提示"],["排队","秒杀请求进入有界队列","队列满时快速拒绝；不超卖"],["恢复","依赖正常后逐步放量","避免同时重试形成恢复风暴"]]}/><Card title="用例标题示例"><p className="font-medium text-text-primary">当库存服务连续失败触发熔断时，商城应停止无效调用，并在半开探测成功后逐步恢复。</p></Card></S>
<S id="backup" n="08" t="用真实恢复证明备份可用" b="备份存在不等于能恢复"><Card title="备份恢复演练步骤"><List ordered items={["选取隔离恢复环境，记录备份版本、时间点、加密和保留策略。","恢复数据库与必要对象存储，不覆盖当前环境。","执行结构校验、行数与控制总额对账。","抽取订单—支付—退款链路做业务级验证。","测量实际 RTO/RPO，检查密钥、权限和应用连接。","销毁临时恢复环境前保存脱敏证据。"]}/></Card><Code title="业务对账示意">{`SELECT COUNT(*) AS orders, SUM(pay_amount) AS paid
FROM orders
WHERE created_at < :restore_point;

-- 与支付流水控制总额、退款累计金额交叉核对`}</Code><Callout>不要用“备份任务成功”替代恢复测试。只有把备份恢复成可运行、可查询、业务关系正确的数据，才证明恢复能力存在。</Callout></S>
<S id="practice" n="09" t="完成一次可审计的故障演练" b="练习与清单"><Card title="练习"><List ordered items={["为商城交易链列出服务、网络、数据库和第三方四类故障。","为每类故障写稳态指标、注入方式、停止条件和恢复步骤。","执行一次单实例宕机和一次 800ms 延迟实验。","完成订单、库存、支付、退款对账并计算 RTO/RPO。","写复盘：假设是否成立，哪道防线失效，下次如何自动验证。"]}/></Card><div className="grid gap-4 md:grid-cols-3"><Check title="安全" items={["范围隔离","操作可撤销","停止条件明确","负责人在线"]}/><Check title="证据" items={["基线已保存","指标日志 Trace 齐全","业务 ID 可串联","恢复时间可计算"]}/><Check title="收尾" items={["故障已撤销","数据已对账","资源回到基线","改进项有负责人"]}/></div></S>
</KnowledgeLayout></div>}

function S({id,n,t,b,children}:{id:string;n:string;t:string;b:string;children:React.ReactNode}){return <section id={id} data-knowledge-section className="mb-14"><div className="mb-5 flex items-center gap-3 border-b-2 border-space-border pb-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-neon-cyan/10 font-mono text-xs text-neon-cyan">{n}</div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold text-text-primary">{t}</h2><span className="rounded-full bg-neon-cyan/10 px-2 py-0.5 text-[10px] text-neon-cyan">{b}</span></div></div>{children}</section>}
function Card({title,children}:{title?:string;children:React.ReactNode}){return <div className="card-glow mb-4 rounded-xl p-5 text-sm leading-7 text-text-secondary">{title&&<h3 className="mb-3 text-base font-bold text-text-primary">{title}</h3>}{children}</div>}
function List({items,ordered=false}:{items:readonly string[];ordered?:boolean}){const T=ordered?"ol":"ul";return <T className={`mt-3 space-y-2 pl-5 ${ordered?"list-decimal":"list-disc"}`}>{items.map(x=><li key={x}>{x}</li>)}</T>}
function Table({title,headers,rows}:{title:string;headers:string[];rows:string[][]}){return <Card title={title}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b border-space-border">{headers.map(x=><th key={x} className="bg-neon-cyan/5 px-4 py-3 text-left text-text-primary">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.join()} className="border-b border-space-border/50">{r.map((x,i)=><td key={x+i} className="px-4 py-2.5 text-xs">{x}</td>)}</tr>)}</tbody></table></div></Card>}
function Code({title,children}:{title:string;children:string}){return <div className="knowledge-code-block mb-4 overflow-hidden rounded-xl border border-space-border"><div className="border-b border-space-border bg-space-card/50 px-4 py-2 text-xs text-text-secondary">{title}</div><pre className="overflow-x-auto p-4 text-[13px]"><code className="text-neon-cyan/80">{children}</code></pre></div>}
function Callout({children}:{children:React.ReactNode}){return <div className="mb-4 border-l-2 border-neon-cyan bg-neon-cyan/5 px-5 py-4 text-sm leading-7 text-text-secondary">{children}</div>}
function Flow({title,items}:{title:string;items:readonly (readonly [string,string])[]}){return <Card title={title}><div className="grid gap-2 md:grid-cols-7 md:items-center">{items.map((x,i)=><div className="contents" key={x[0]}><div className="rounded-lg border border-space-border bg-space-card/50 p-4 text-center"><strong className="block text-sm text-text-primary">{x[0]}</strong><span className="text-xs">{x[1]}</span></div>{i<3&&<ArrowRight className="mx-auto hidden h-4 w-4 text-neon-cyan md:block"/>}</div>)}</div></Card>}
function Timeline({items}:{items:string[][]}){return <Card title="故障响应时间线"><div className="grid gap-3 md:grid-cols-4">{items.map(x=><div key={x[0]} className="rounded-lg border border-space-border bg-space-card/50 p-4"><b className="text-neon-cyan">{x[0]}</b><p className="mt-2 text-xs">{x[1]}</p></div>)}</div></Card>}
function Check({title,items}:{title:string;items:string[]}){return <Card title={title}><ul className="space-y-3">{items.map(x=><li className="flex gap-2" key={x}><CheckCircle2 className="mt-1 h-4 w-4 text-neon-cyan"/>{x}</li>)}</ul></Card>}
