import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import { KnowledgeLayout, type SectionItem } from "@/components/KnowledgeLayout";
import { buildPageMetadata } from "@/lib/site";
import { cn } from "@/lib/cn";

export const metadata = buildPageMetadata({ title: "业务状态流转测试实战教程", description: "围绕商城订单、支付和退款的状态流转，学习合法与非法转换、并发、幂等、回滚、补偿和数据一致性测试。", path: "/knowledge/business-state-machine-testing", tags: ["状态流转测试", "状态迁移测试", "订单测试", "支付测试", "退款测试", "幂等性"] });
const sections: SectionItem[] = [{ id: "concept", label: "状态流转基础" }, { id: "model", label: "梳理状态" }, { id: "valid", label: "合法流转" }, { id: "invalid", label: "非法流转" }, { id: "concurrency", label: "并发竞争" }, { id: "idempotency", label: "重复与幂等" }, { id: "rollback", label: "回滚补偿" }, { id: "consistency", label: "一致性验证" }, { id: "practice", label: "练习与检查" }];
const transitionRows = [["待支付", "支付成功", "已支付", "支付记录成功，库存保持已扣减"], ["待支付", "用户取消", "已取消", "释放库存，优惠券可恢复"], ["待支付", "超时关闭", "已关闭", "拒绝后续普通支付"], ["已支付", "申请退款", "退款中", "创建一笔退款单"], ["退款中", "渠道退款成功", "已退款", "资金、订单和退款单一致"]];
const invalidRows = [["已取消 → 已支付", "迟到的支付成功回调", "拒绝直接覆盖；进入异常处理或补偿"], ["已退款 → 退款中", "重复点击退款", "返回原退款结果，不新建退款单"], ["待支付 → 已退款", "跳过支付直接改状态", "拒绝并记录审计"], ["已支付 → 待支付", "人工错误回退", "禁止普通接口逆向迁移"]];

export default function BusinessStateMachineTestingPage() { return <div className="mx-auto max-w-5xl animate-fade-in">
      <Link href="/knowledge/web-functional-testing" className="mb-8 inline-flex items-center gap-2 text-sm text-text-secondary transition-colors hover:text-neon-cyan"><ArrowLeft className="h-4 w-4" />返回 Web 功能测试</Link>
  <KnowledgeLayout sections={sections} searchPlaceholder="搜索状态流转测试关键词...">
    <header className="mb-10"><div className="mb-3 font-mono text-[10px] uppercase tracking-[0.22em] text-neon-cyan">Main Track / Tutorial 07</div><h1 className="mb-3 bg-gradient-to-r from-neon-cyan to-neon-purple bg-clip-text text-3xl font-bold text-transparent md:text-4xl">业务状态流转测试实战教程</h1><p className="mb-6 text-lg leading-8 text-text-secondary">把订单看成“当前状态 + 触发操作 + 流转规则”，验证支付、取消和退款在正常、重复、乱序与并发下是否仍然正确。</p><div className="flex flex-wrap gap-6 text-sm text-text-secondary"><span>9 个章节</span><span>订单支付退款</span><span>状态流转 + 并发 + 补偿</span></div></header>
    <section id="concept" data-knowledge-section className="mb-14"><SectionHeader number="01" title="为什么复杂业务要明确状态流转" badge="不只测试页面按钮" /><Card title="当前状态决定接下来允许做什么"><p>订单处于“待支付”时可以支付或取消；进入“已支付”后可以履约或退款，却不应回到普通待支付。把当前状态、触发操作和目标状态整理成规则，专业上称为“状态迁移测试”，部分资料也称“状态机测试”。</p></Card><StateFlow /><div className="grid gap-4 md:grid-cols-3"><Card title="当前状态"><p>某一时刻可以稳定观察的业务阶段。</p></Card><Card title="触发操作"><p>用户、定时任务或外部回调发起的动作。</p></Card><Card title="流转规则"><p>允许条件、目标状态、数据副作用和失败处理。</p></Card></div></section>
    <section id="model" data-knowledge-section className="mb-14"><SectionHeader number="02" title="从需求建立状态模型" badge="先穷举再执行" /><Card title="建模步骤"><BulletList ordered items={["找出订单、支付单、退款单三个状态主体。", "列出每个主体所有可观察状态。", "标出用户操作、超时任务和渠道回调事件。", "为每次迁移写前置、目标状态和副作用。", "补上失败、重复、乱序和人工处理路径。"]} /></Card><TableCard title="订单合法迁移表" headers={["当前状态", "事件", "目标状态", "关键副作用"]} rows={transitionRows} /><Callout>状态名称要能由接口或数据查询证实。“处理中”若没有明确进入和退出条件，就还不是可测试的状态定义。</Callout></section>
    <section id="valid" data-knowledge-section className="mb-14"><SectionHeader number="03" title="覆盖每一条合法状态迁移" badge="节点与边都要测" /><TransitionFigure /><Card title="合法迁移用例"><BulletList items={["当待支付订单完成支付时，订单进入已支付且支付记录成功。", "当待支付订单超过有效期时，订单关闭并释放库存。", "当已支付订单满足退款条件时，创建退款单并进入退款中。", "当退款渠道返回成功时，订单进入已退款且金额一致。"]} /></Card><Card title="每条迁移至少验证"><BulletList items={["事件前状态与权限满足前提。", "接口返回 HTTP 200 后，业务码说明本次业务是否受理。", "主体进入唯一目标状态。", "库存、金额、优惠券和消息副作用正确。", "页面能够展示最新状态且操作入口同步变化。"]} /></Card></section>
    <section id="invalid" data-knowledge-section className="mb-14"><SectionHeader number="04" title="主动验证非法迁移" badge="不能走的路同样重要" /><TableCard title="非法迁移与预期防线" headers={["非法迁移", "触发方式", "预期"]} rows={invalidRows} /><Card title="执行方式"><BulletList ordered items={["通过测试接口或可控工具准备指定状态。", "发起在当前状态不允许的事件。", "确认接口拒绝且返回明确业务原因。", "核对订单及关联数据完全不变。", "检查审计日志和告警是否满足设计。"]} /></Card></section>
    <section id="concurrency" data-knowledge-section className="mb-14"><SectionHeader number="05" title="制造并发事件和竞争条件" badge="顺序不同，结果仍要守约束" /><RaceFigure /><Card title="关键并发用例"><BulletList items={["当支付成功和超时关闭几乎同时发生时，订单只进入一个合法终态。", "当用户 A 与客服同时发起退款时，只创建一笔有效退款。", "当两个设备同时提交最后一件库存时，只允许一笔订单占用成功。", "当支付回调与用户查询并发时，查询不得展示不存在的中间组合。"]} /></Card><Callout>并发测试要记录每个请求的发送时间、幂等键、request_id 和最终数据；只看两次页面点击无法证明竞争条件。</Callout></section>
    <section id="idempotency" data-knowledge-section className="mb-14"><SectionHeader number="06" title="验证重复提交与幂等" badge="相同意图只产生一次结果" /><FlowFigure id="idempotency-flow" title="幂等处理的核心路径" items={[["首次请求", "携带幂等键"], ["保存结果", "状态与响应"], ["重复请求", "识别相同意图"], ["返回原结果", "不重复副作用"]]} /><TableCard title="幂等检查" headers={["场景", "操作", "必须成立"]} rows={[["重复下单", "同一幂等键连续提交", "只有一个订单，库存只扣一次"], ["重复支付", "按钮双击或网络重试", "只有一笔有效支付"], ["重复回调", "渠道发送相同通知", "状态不二次推进"], ["重复退款", "相同退款请求重放", "金额不累计，返回原退款单"]]} /></section>
    <section id="rollback" data-knowledge-section className="mb-14"><SectionHeader number="07" title="测试失败回滚与异步补偿" badge="失败后仍能恢复" /><CompensationFigure /><Card title="故障场景"><BulletList items={["当订单创建后库存扣减失败时，订单不进入可支付状态或被可靠关闭。", "当支付成功但订单更新失败时，补偿任务根据支付事实推进订单。", "当退款成功但消息发送失败时，可重试消息且不重复退款。", "当补偿连续失败时，系统告警并进入可人工处理状态。"]} /></Card><Callout>回滚适合尚未对外生效的本地操作；外部支付已经成功时不能假装回滚资金，必须通过补偿和对账恢复一致。</Callout></section>
    <section id="consistency" data-knowledge-section className="mb-14"><SectionHeader number="08" title="核对跨对象状态与数据一致性" badge="一个订单，多份事实" /><TableCard title="终态一致性断言" headers={["订单状态", "支付单", "退款单", "库存与优惠券"]} rows={[["待支付", "未支付", "不存在", "按规则锁定"], ["已支付", "成功且金额一致", "不存在", "库存已扣，优惠已使用"], ["已取消/关闭", "无成功支付", "不存在", "库存与优惠已释放"], ["退款中", "支付成功", "处理中", "按业务约定处理"], ["已退款", "支付成功", "成功且不超实付", "按规则恢复"]]} /><Card title="可执行核对"><BulletList ordered items={["保存订单号、支付单号和退款单号。", "查询接口返回的当前状态和业务码。", "核对数据库中的主体版本、金额和更新时间。", "检查库存、优惠券、消息和账务副作用。", "在最终一致性时间窗后再次查询。", "超时仍不一致时保存证据并触发告警。"]} /></Card></section>
    <section id="practice" data-knowledge-section className="mb-14"><SectionHeader number="09" title="完成一套订单状态流转测试" badge="从规则到证据" /><Card title="练习"><BulletList ordered items={["画出待支付、已支付、已取消、退款中和已退款。", "为每条合法流转写一条“当……时，……”用例。", "补充四条非法流转并验证数据不变。", "设计支付与关单、退款与重复回调两个竞争场景。", "验证下单、支付和退款的幂等键。", "模拟订单更新失败并检查补偿与告警。"]} /></Card><div className="grid gap-4 md:grid-cols-3"><ChecklistCard title="规则完整" items={["状态可观察", "操作已穷举", "终态明确", "副作用明确"]} /><ChecklistCard title="异常充分" items={["非法流转拒绝", "并发终态唯一", "重复请求幂等", "乱序可处理"]} /><ChecklistCard title="结果可信" items={["多对象一致", "补偿可验证", "告警可触发", "证据可追溯"]} /></div><NextLink text="理解业务状态流转后，下一篇把同一交易链路放到真实移动设备、系统权限和弱网环境中验证。" href="/knowledge/mobile-app-testing" label="继续学习移动端 App 测试" /></section>
  </KnowledgeLayout>
</div>; }

function SectionHeader({ number, title, badge }: { number: string; title: string; badge: string }) { return <div className="mb-5 flex items-center gap-3 border-b-2 border-space-border pb-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-neon-cyan/10 font-mono text-xs text-neon-cyan">{number}</div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold text-text-primary">{title}</h2><span className="rounded-full bg-neon-cyan/10 px-2 py-0.5 text-[10px] font-medium text-neon-cyan">{badge}</span></div></div>; }
function Card({ title, children }: { title?: string; children: React.ReactNode }) { return <div className="card-glow mb-4 rounded-xl p-5 text-sm leading-7 text-text-secondary">{title && <h3 className="mb-3 text-base font-bold text-text-primary">{title}</h3>}{children}</div>; }
function BulletList({ items, ordered = false }: { items: readonly string[]; ordered?: boolean }) { const Tag = ordered ? "ol" : "ul"; return <Tag className={cn("mt-3 space-y-2 pl-5", ordered ? "list-decimal" : "list-disc")}>{items.map((item) => <li key={item}>{item}</li>)}</Tag>; }
function TableCard({ title, headers, rows }: { title: string; headers: readonly string[]; rows: readonly string[][] }) { return <Card title={title}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b border-space-border">{headers.map((header) => <th key={header} className="bg-neon-cyan/5 px-4 py-3 text-left font-semibold text-text-primary">{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.join("-")} className="border-b border-space-border/50 last:border-b-0">{row.map((cell, index) => <td key={`${cell}-${index}`} className="px-4 py-2.5 text-xs leading-relaxed">{cell}</td>)}</tr>)}</tbody></table></div></Card>; }
function Callout({ children }: { children: React.ReactNode }) { return <div className="mb-4 border-l-2 border-neon-cyan bg-neon-cyan/5 px-5 py-4 text-sm leading-7 text-text-secondary">{children}</div>; }
function FlowFigure({ id, title, items }: { id: string; title: string; items: readonly (readonly [string, string])[] }) { return <figure className="card-glow mb-4 rounded-xl p-5" aria-labelledby={id}><figcaption id={id} className="mb-5 text-sm font-bold text-text-primary">{title}</figcaption><div className="grid gap-2 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{items.map((item, index) => <div key={item[0]} className="contents"><div className="rounded-lg border border-space-border bg-space-card/50 p-4 text-center"><strong className="block text-sm text-text-primary">{item[0]}</strong><span className="mt-2 block text-xs text-text-secondary">{item[1]}</span></div>{index < items.length - 1 && <ArrowRight className="mx-auto hidden h-4 w-4 text-neon-cyan md:block" />}</div>)}</div></figure>; }
function StateFlow() { return <figure className="card-glow mb-4 rounded-xl p-5" aria-labelledby="state-title"><figcaption id="state-title" className="mb-5 text-sm font-bold text-text-primary">简化订单状态图</figcaption><div className="grid gap-3 md:grid-cols-3"><div className="rounded-lg border border-space-border bg-space-card/50 p-4 text-center"><strong className="text-text-primary">待支付</strong><p className="mt-2 text-xs text-text-secondary">支付 → 已支付<br />取消/超时 → 已关闭</p></div><div className="rounded-lg border border-neon-cyan/50 bg-neon-cyan/10 p-4 text-center"><strong className="text-text-primary">已支付</strong><p className="mt-2 text-xs text-text-secondary">申请退款 → 退款中</p></div><div className="rounded-lg border border-space-border bg-space-card/50 p-4 text-center"><strong className="text-text-primary">退款中</strong><p className="mt-2 text-xs text-text-secondary">渠道成功 → 已退款<br />渠道失败 → 可重试</p></div></div></figure>; }
function TransitionFigure() { return <FlowFigure id="transition-title" title="一条迁移的完整断言" items={[["前置状态", "待支付"], ["触发事件", "支付成功"], ["目标状态", "已支付"], ["业务副作用", "支付记录与通知"]]} />; }
function RaceFigure() { return <figure className="card-glow mb-4 rounded-xl p-5" aria-labelledby="race-title"><figcaption id="race-title" className="mb-5 text-sm font-bold text-text-primary">支付成功与超时关单竞争</figcaption><div className="grid gap-3 md:grid-cols-[1fr_1fr_1fr]"><div className="rounded-lg border border-space-border bg-space-card/50 p-4"><strong className="text-text-primary">事件 A</strong><p className="mt-2 text-xs text-text-secondary">支付渠道回调成功</p></div><div className="rounded-lg border border-space-border bg-space-card/50 p-4"><strong className="text-text-primary">事件 B</strong><p className="mt-2 text-xs text-text-secondary">超时任务尝试关单</p></div><div className="rounded-lg border border-neon-cyan/50 bg-neon-cyan/10 p-4"><strong className="text-text-primary">唯一终态</strong><p className="mt-2 text-xs text-text-secondary">按锁、版本或规则只接受一条迁移</p></div></div></figure>; }
function CompensationFigure() { return <FlowFigure id="compensation-title" title="外部成功后的恢复路径" items={[["支付已成功", "外部事实"], ["订单更新失败", "局部异常"], ["记录待补偿", "可追踪"], ["重试或人工", "恢复一致"]]} />; }
function ChecklistCard({ title, items }: { title: string; items: readonly string[] }) { return <Card title={title}><ul className="space-y-3">{items.map((item) => <li key={item} className="flex items-start gap-2"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-neon-cyan" /><span>{item}</span></li>)}</ul></Card>; }
function NextLink({ text, href, label }: { text: string; href: string; label: string }) { return <div className="mt-8 flex flex-wrap items-center justify-between gap-4 border-y border-space-border py-6"><p className="text-sm text-text-secondary">{text}</p><Link href={href} className="inline-flex items-center gap-2 text-sm text-neon-cyan">{label}<ArrowRight className="h-4 w-4" /></Link></div>; }
