import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import { KnowledgeLayout, type SectionItem } from "@/components/KnowledgeLayout";
import { buildPageMetadata } from "@/lib/site";
import { cn } from "@/lib/cn";

export const metadata = buildPageMetadata({ title: "Bug 管理与缺陷分析教程", description: "通过商城下单、支付和退款问题，学习缺陷识别、报告、分级、流转、定位、回归与复盘。", path: "/knowledge/defect-management-analysis", tags: ["Bug 管理", "缺陷分析", "缺陷报告", "根因分析", "回归测试"] });
const sections: SectionItem[] = [{ id: "judge", label: "判断缺陷" }, { id: "report", label: "缺陷报告" }, { id: "evidence", label: "证据链" }, { id: "severity", label: "等级优先级" }, { id: "lifecycle", label: "缺陷流转" }, { id: "diagnose", label: "分层定位" }, { id: "regression", label: "修复回归" }, { id: "rca", label: "根因复盘" }, { id: "practice", label: "练习与检查" }];
const reportRows = [["标题", "当支付按钮连续点击时，系统生成两笔支付单", "条件 + 动作 + 错误结果"], ["环境", "测试环境 / Chrome / 会员账号 A", "版本、设备、账号类型"], ["前置", "订单待支付，应付 100 元", "可恢复到同一初始状态"], ["步骤", "进入收银台，连续点击支付两次", "编号且只保留必要动作"], ["实际", "出现两笔支付单，均为处理中", "只陈述观察事实"], ["预期", "仅一笔有效支付单，重复请求返回同一结果", "对应确认过的规则"], ["证据", "时间、订单号、请求、日志、录屏", "支持复现和定位"]];
const classifyRows = [["产品问题", "退款规则前后矛盾", "回到需求结论，补齐验收标准"], ["代码缺陷", "重复回调导致重复退款", "提交缺陷并定位幂等处理"], ["数据问题", "测试商品没有库存", "修复或重建可控测试数据"], ["环境问题", "支付沙箱不可达", "记录阻塞，交由环境负责人处理"]];

export default function DefectManagementAnalysisPage() { return <div className="mx-auto max-w-5xl animate-fade-in">
      <Link href="/knowledge/requirements-test-planning" className="mb-8 inline-flex items-center gap-2 text-sm text-text-secondary transition-colors hover:text-neon-cyan"><ArrowLeft className="h-4 w-4" />返回需求评审与测试方案</Link>
  <KnowledgeLayout sections={sections} searchPlaceholder="搜索缺陷管理关键词...">
    <header className="mb-10"><div className="mb-3 font-mono text-[10px] uppercase tracking-[0.22em] text-neon-cyan">Main Track / Tutorial 05</div><h1 className="mb-3 bg-gradient-to-r from-neon-cyan to-neon-purple bg-clip-text text-3xl font-bold text-transparent md:text-4xl">Bug 管理与缺陷分析教程</h1><p className="mb-6 text-lg leading-8 text-text-secondary">让一个异常从“看起来不对”变成可复现、可定位、可回归、能推动质量改进的工程事实。</p><div className="flex flex-wrap gap-6 text-sm text-text-secondary"><span>9 个章节</span><span>交易缺陷闭环</span><span>报告 + 定位 + 复盘</span></div></header>
    <section id="judge" data-knowledge-section className="mb-14"><SectionHeader number="01" title="先判断它是不是缺陷" badge="事实对照标准" /><Card title="缺陷来自实际与预期的差异"><p>当退款页面提示“成功”，但退款单仍为处理中，你需要先找到明确预期，再确认环境、数据和操作是否有效。没有依据时先记录疑问，不要把个人偏好直接写成 Bug。</p></Card><FlowFigure id="judge-flow" title="异常确认的最短闭环" items={[["观察现象", "页面或数据异常"], ["核对依据", "需求与验收标准"], ["排除干扰", "环境、数据、操作"], ["稳定复现", "记录最小步骤"]]} /><TableCard title="先区分问题来源" headers={["类型", "商城示例", "处理方式"]} rows={classifyRows} /></section>
    <section id="report" data-knowledge-section className="mb-14"><SectionHeader number="02" title="写一份别人能复现的缺陷报告" badge="信息完整但不堆砌" /><TableCard title="重复支付缺陷报告" headers={["字段", "示例", "写法"]} rows={reportRows} /><Card title="可执行步骤"><BulletList ordered items={["从干净数据开始再复现一次。", "压缩到仍能触发问题的最少步骤。", "用“当……时，……”写标题。", "分别记录预期和实际，不写原因猜测。", "附上可搜索的业务 ID 和时间。"]} /></Card></section>
    <section id="evidence" data-knowledge-section className="mb-14"><SectionHeader number="03" title="建立页面、请求、日志和数据证据链" badge="同一次复现" /><FlowFigure id="evidence-flow" title="用标识串起一次支付异常" items={[["页面", "错误提示与时间"], ["请求", "HTTP 与业务码"], ["日志", "request_id / trace_id"], ["数据", "订单与支付记录"]]} /><Card title="响应证据怎么解释"><p>支付接口返回 HTTP 200，只能说明服务正常处理了请求；还要检查业务码、支付单状态和是否发生扣款。HTTP 成功与业务成功必须分开记录。</p></Card><Callout>分享证据前移除令牌、密码、银行卡号和个人信息；不要在缺陷标题中暴露敏感数据。</Callout></section>
    <section id="severity" data-knowledge-section className="mb-14"><SectionHeader number="04" title="分清严重程度与修复优先级" badge="影响和顺序不是一回事" /><SeverityFigure /><TableCard title="商城缺陷分级" headers={["问题", "严重程度", "优先级与理由"]} rows={[["重复扣款", "致命", "P0：资金损失，阻断发布"], ["支付成功订单未更新", "严重", "P0：无法履约且需要补偿"], ["退款记录排序错误", "一般", "P1：影响客服处理效率"], ["按钮文字轻微偏移", "提示", "P2：不阻断核心流程"]]} /><Callout>等级争议要回到用户影响、数据影响、发生范围、恢复成本和发布窗口，不用职位或情绪决定。</Callout></section>
    <section id="lifecycle" data-knowledge-section className="mb-14"><SectionHeader number="05" title="让缺陷在生命周期中有明确责任" badge="状态不是进度装饰" /><FlowFigure id="life-flow" title="典型缺陷流转" items={[["新建", "证据完整"], ["确认", "归属与优先级"], ["修复", "说明原因和影响"], ["回归", "原问题与关联范围"], ["关闭", "证据可追溯"]]} /><Card title="退回时写清原因"><BulletList items={["无法复现：补充缺失环境和数据，并约定再次验证。", "重复缺陷：关联原缺陷，保留新场景证据。", "按设计：引用已确认规则；若规则不合理转产品问题。", "延期处理：记录风险接受人、目标版本和临时措施。"]} /></Card></section>
    <section id="diagnose" data-knowledge-section className="mb-14"><SectionHeader number="06" title="按层定位，不把猜测当结论" badge="先证据后归因" /><LayerFigure /><Card title="退款失败的定位顺序"><BulletList ordered items={["确认页面是否发出退款请求。", "检查金额、订单号与幂等键。", "区分 HTTP 失败和业务拒绝。", "用 request_id 查服务日志与下游响应。", "核对订单、支付单、退款单和消息。", "基于证据标记产品、代码、数据或环境问题。"]} /></Card><Card title="定位型用例"><BulletList items={["当订单不属于当前用户时，退款请求被拒绝且订单数据不变。", "当相同幂等键重复提交时，只存在一笔有效退款单。", "当支付渠道超时时，退款保持可恢复状态并可被补偿任务处理。"]} /></Card></section>
    <section id="regression" data-knowledge-section className="mb-14"><SectionHeader number="07" title="回归不只重跑原步骤" badge="围绕修改影响面" /><div className="grid gap-4 md:grid-cols-3"><Card title="确认修复"><p>使用原环境与原数据条件，确认重复支付不再发生。</p></Card><Card title="扩展同类"><p>覆盖刷新、双端操作、接口重放和回调重复。</p></Card><Card title="检查相邻"><p>回归正常支付、取消支付、退款与订单查询。</p></Card></div><ChecklistCard title="关闭前检查" items={["原缺陷稳定通过", "相邻路径没有回归", "数据与日志结果一致", "修复版本和证据已记录"]} /></section>
    <section id="rca" data-knowledge-section className="mb-14"><SectionHeader number="08" title="从根因复盘走向预防" badge="不止归咎个人" /><FlowFigure id="rca-flow" title="从缺陷到改进" items={[["触发现象", "重复退款"], ["技术根因", "幂等校验缺失"], ["流程根因", "评审未覆盖重试"], ["预防动作", "模板、测试与监控"]]} /><Card title="五问示例"><BulletList ordered items={["为什么重复退款？重复回调被再次执行。", "为什么会再次执行？服务没有持久化幂等结果。", "为什么没有设计？接口评审没有异常重试项。", "为什么评审漏掉？模板只覆盖正常流程。", "如何预防？增加幂等设计清单、自动化用例与重复退款告警。"]} /></Card></section>
    <section id="practice" data-knowledge-section className="mb-14"><SectionHeader number="09" title="完成一次缺陷闭环练习" badge="从发现到预防" /><Card title="练习：支付成功但订单仍待支付"><BulletList ordered items={["写一条“当……时，……”格式的缺陷标题。", "补齐环境、前置、步骤、实际、预期和证据。", "判断严重程度与优先级并说明理由。", "列出页面、请求、日志和数据的取证项。", "设计原缺陷、同类场景和相邻功能回归。", "用五问法给出可验证的预防动作。"]} /></Card><div className="grid gap-4 md:grid-cols-3"><ChecklistCard title="可复现" items={["起始状态明确", "步骤最小", "预期有依据", "证据同源"]} /><ChecklistCard title="可推进" items={["等级有理由", "归属有证据", "状态有责任人", "延期有风险接受"]} /><ChecklistCard title="可改进" items={["回归有范围", "根因不猜测", "措施可验证", "结论可追溯"]} /></div><NextLink text="缺陷闭环之后，进入用户日常接触最多的 Web 功能测试。" href="/knowledge/web-functional-testing" label="继续学习 Web 功能测试" /></section>
  </KnowledgeLayout>
</div>; }

function SectionHeader({ number, title, badge }: { number: string; title: string; badge: string }) { return <div className="mb-5 flex items-center gap-3 border-b-2 border-space-border pb-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-neon-cyan/10 font-mono text-xs text-neon-cyan">{number}</div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold text-text-primary">{title}</h2><span className="rounded-full bg-neon-cyan/10 px-2 py-0.5 text-[10px] font-medium text-neon-cyan">{badge}</span></div></div>; }
function Card({ title, children }: { title?: string; children: React.ReactNode }) { return <div className="card-glow mb-4 rounded-xl p-5 text-sm leading-7 text-text-secondary">{title && <h3 className="mb-3 text-base font-bold text-text-primary">{title}</h3>}{children}</div>; }
function BulletList({ items, ordered = false }: { items: readonly string[]; ordered?: boolean }) { const Tag = ordered ? "ol" : "ul"; return <Tag className={cn("mt-3 space-y-2 pl-5", ordered ? "list-decimal" : "list-disc")}>{items.map((item) => <li key={item}>{item}</li>)}</Tag>; }
function TableCard({ title, headers, rows }: { title: string; headers: readonly string[]; rows: readonly string[][] }) { return <Card title={title}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b border-space-border">{headers.map((header) => <th key={header} className="bg-neon-cyan/5 px-4 py-3 text-left font-semibold text-text-primary">{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.join("-")} className="border-b border-space-border/50 last:border-b-0">{row.map((cell, index) => <td key={`${cell}-${index}`} className="px-4 py-2.5 text-xs leading-relaxed">{cell}</td>)}</tr>)}</tbody></table></div></Card>; }
function Callout({ children }: { children: React.ReactNode }) { return <div className="mb-4 border-l-2 border-neon-cyan bg-neon-cyan/5 px-5 py-4 text-sm leading-7 text-text-secondary">{children}</div>; }
function FlowFigure({ id, title, items }: { id: string; title: string; items: readonly (readonly [string, string])[] }) { return <figure className="card-glow mb-4 rounded-xl p-5" aria-labelledby={id}><figcaption id={id} className="mb-5 text-sm font-bold text-text-primary">{title}</figcaption><div className={cn("grid gap-2 md:items-center", items.length === 5 ? "md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr_auto_1fr]" : "md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr]")}>{items.map((item, index) => <div key={item[0]} className="contents"><div className="rounded-lg border border-space-border bg-space-card/50 p-4 text-center"><strong className="block text-sm text-text-primary">{item[0]}</strong><span className="mt-2 block text-xs text-text-secondary">{item[1]}</span></div>{index < items.length - 1 && <ArrowRight className="mx-auto hidden h-4 w-4 text-neon-cyan md:block" />}</div>)}</div></figure>; }
function SeverityFigure() { return <figure className="card-glow mb-4 rounded-xl p-5" aria-labelledby="severity-title"><figcaption id="severity-title" className="mb-5 text-sm font-bold text-text-primary">两个维度分别回答不同问题</figcaption><div className="grid gap-3 md:grid-cols-2"><div className="rounded-lg border border-neon-cyan/50 bg-neon-cyan/10 p-5"><strong className="text-text-primary">严重程度</strong><p className="mt-2 text-xs text-text-secondary">问题造成多大用户、业务、资金或数据影响。</p></div><div className="rounded-lg border border-space-border bg-space-card/50 p-5"><strong className="text-text-primary">修复优先级</strong><p className="mt-2 text-xs text-text-secondary">结合影响、发布窗口和替代方案决定多快处理。</p></div></div></figure>; }
function LayerFigure() { const items = [["页面层", "交互、提示、展示"], ["接口层", "参数、HTTP、业务码"], ["服务层", "日志、调用、异常"], ["数据层", "订单、支付、退款"]]; return <figure className="card-glow mb-4 rounded-xl p-5" aria-labelledby="layer-title"><figcaption id="layer-title" className="mb-5 text-sm font-bold text-text-primary">从现象逐层收窄责任范围</figcaption><div className="grid gap-3 md:grid-cols-4">{items.map((item, i) => <div key={item[0]} className="rounded-lg border border-space-border bg-space-card/50 p-4"><span className="font-mono text-[9px] text-neon-cyan">0{i + 1}</span><strong className="my-2 block text-sm text-text-primary">{item[0]}</strong><p className="text-xs text-text-secondary">{item[1]}</p></div>)}</div></figure>; }
function ChecklistCard({ title, items }: { title: string; items: readonly string[] }) { return <Card title={title}><ul className="space-y-3">{items.map((item) => <li key={item} className="flex items-start gap-2"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-neon-cyan" /><span>{item}</span></li>)}</ul></Card>; }
function NextLink({ text, href, label }: { text: string; href: string; label: string }) { return <div className="mt-8 flex flex-wrap items-center justify-between gap-4 border-y border-space-border py-6"><p className="text-sm text-text-secondary">{text}</p><Link href={href} className="inline-flex items-center gap-2 text-sm text-neon-cyan">{label}<ArrowRight className="h-4 w-4" /></Link></div>; }
