import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import { KnowledgeLayout, type SectionItem } from "@/components/KnowledgeLayout";
import { buildPageMetadata } from "@/lib/site";

export const metadata = buildPageMetadata({ title: "测试资产工程与版本追溯教程", description: "把需求规则、测试点、风险、用例、缺陷模式、评审和版本总结连接成可追溯、可校验、可复用的测试资产体系。", path: "/knowledge/test-assets-traceability", tags: ["测试资产", "需求追溯", "版本管理", "质量门禁"] });
const sections: SectionItem[] = [{id:"chain",label:"资产链"},{id:"rules",label:"规则注册表"},{id:"risks",label:"风险规则"},{id:"defects",label:"缺陷模式"},{id:"version",label:"版本追溯"},{id:"deliverables",label:"交付物"},{id:"gates",label:"质量门禁"},{id:"reuse",label:"取用与回填"},{id:"practice",label:"练习清单"}];

export default function TestAssetsPage(){return <div className="mx-auto max-w-5xl animate-fade-in"><Link href="/knowledge/tutorials?track=quality-architecture" className="mb-8 inline-flex items-center gap-2 text-sm text-text-secondary hover:text-neon-cyan"><ArrowLeft className="h-4 w-4"/>返回质量体系与测试架构模块</Link><KnowledgeLayout sections={sections} searchPlaceholder="搜索规则、风险、缺陷模式与版本追溯...">
<Header/>
<S id="chain" n="01" t="测试资产不是一堆文件，而是一条证据链" b="上下游必须接得上"><Flow items={[["需求规则","为什么要测"],["测试点与风险","具体测什么"],["测试用例","怎样执行"],["缺陷与评审","发现了什么"],["版本总结","留下什么"]]}/><Card title="贯穿问题"><p>某模块已有近百条用例，校验也全部通过，但新版需求逐条对照后，完整覆盖不足四成。问题不在用例数量，而在用例没有挂接需求规则，校验只能检查“已有内容是否正确”，看不见“应该存在但缺失的内容”。</p></Card><Callout>资产工程的目标，是让每条结论都能回答来源、版本、责任和下一步，而不是让目录看起来很完整。</Callout></S>
<S id="rules" n="02" t="先把需求拆成可核对的规则" b="覆盖率的分母"><Table title="规则注册表最小字段" headers={["字段","用途","示例"]} rows={[["rule_id","稳定引用规则","REQ-V2-4.2.1"],["version","说明规则在哪版生效","V2.0"],["source","保留原文位置","需求 §4.2.1"],["statement","写成可测试约束","无下载权限不得生成报告"],["status","确定、待确认、已删除","确定"],["case_ids","关联验证证据","TC-081、TC-082"]]}/><Card title="为什么规则先于用例"><List items={["覆盖率有明确分母，不再用用例数量冒充覆盖。","需求变更时可以反查受影响的测试点和用例。","待确认项不会混进确定规则，减少按猜测写用例。","机器校验可以发现某个模块规则为空，而不是静默全绿。"]}/></Card></S>
<S id="risks" n="03" t="把通用测试点和风险规则分开管理" b="基础覆盖 + 风险补漏"><Table title="两类资产各自解决什么" headers={["资产","内容","使用方式"]} rows={[["通用测试点库","必填、唯一性、分页、空态、重复提交、权限四层","按功能形态匹配基础覆盖"],["风险规则库","触发条件、可能失效方式、建议方法与优先级","命中条件后补充风险用例"],["待确认清单","需求冲突、缺失数值、跨端口径差异","确认后回写规则与用例"]]}/><Card title="规则不得臆造数值"><p>需求只说“会话超时后重新登录”，就不能自行写成“30 分钟后失效”。测试点应写为“在配置的超时时长后访问受保护资源应被拒绝”，同时把具体时长列入待确认。</p></Card></S>
<S id="defects" n="04" t="把历史缺陷提炼成可复用模式" b="防止换张脸复发"><Table title="缺陷到检查点的转换" headers={["缺陷现象","抽象模式","回归检查点"]} rows={[["角色名称重复仍可保存","唯一性校验遗漏","新增与编辑都验证唯一；空格与大小写口径一致"],["完成状态仍可编辑","状态流转限制缺失","每个状态核对按钮、接口和数据可变更性"],["连续提交生成多条数据","重复提交未做幂等","连续点击、刷新重提、重复请求只生效一次"],["用户看到他人数据","权限数据范围错误","角色 × 数据归属矩阵覆盖列表、详情、操作与导出"]]}/><Card title="模式库的结构"><List items={["症状：用户实际看到什么。","可能成因：用于定位，不在未经确认时当事实。","易发场景：什么改动会再次触发。","测试设计建议：如何转成可执行检查点。","关联缺陷与验证版本：证明它从哪里来、何时有效。"]}/></Card></S>
<S id="version" n="05" t="用差异表驱动版本增量测试" b="先对照，再改用例"><Table title="版本差异三类" headers={["类型","处理","用例来源标识"]} rows={[["新增","补规则、测试点和用例","新增"],["口径变更","反查旧用例并修订断言","修改"],["规则未变","确认仍适用后继续使用","复用"],["历史缺陷防复发","由模式库生成检查点","回归"],["功能删除或弱化","显式记录合理不覆盖","废弃"]]}/><Flow items={[["新旧需求差异","逐条列变化"],["覆盖核对","规则→测试点→用例"],["人工裁决","覆盖/部分/不覆盖"],["补齐与校验","缺口关闭后提测"]]}/><Callout>“合理不覆盖”也要留结论。它与忘记测试的区别，就是有明确规则、版本和裁决记录。</Callout></S>
<S id="deliverables" n="06" t="七类交付物围绕同一条主线" b="不是七份孤立文档"><Table title="交付物与责任" headers={["交付物","回答的问题","必须关联"]} rows={[["测试点清单","测什么","规则、风险"],["风险清单","哪里可能出错","测试点、回归检查点"],["测试用例","怎样验证","规则、测试点、来源"],["冒烟清单","版本是否值得继续测","主用例 P0 编号"],["评审记录","哪些问题被发现和修订","用例、决议、行动项"],["待确认清单","哪些口径尚未确定","需求章节、影响用例"],["版本总结","结果与下一版行动","前六类产物统计"]]}/><Card title="交付前先对账"><p>测试点数量、风险关闭情况、用例来源分布、冒烟编号、评审修订和总结中的统计必须互相对得上。数字对不上，通常意味着追溯链已经断了。</p></Card></S>
<S id="gates" n="07" t="机器查确定性问题，人判断业务语义" b="双层质量门禁"><Table title="机器适合检查" headers={["门禁","硬问题"]} rows={[["完整性","模块存在用例却没有规则或测试设计"],["需求追溯","确定规则没有任何用例证据"],["冲突","用例违背需求数值、枚举或权限约束"],["格式与去重","编号重复、弱标题、必填字段缺失、疑似重复"],["分布","优先级或来源分布异常，仅作为复核信号"]]}/><Table title="人工必须判断" headers={["问题","原因"]} rows={[["场景是否真正有价值","脚本只能看到字段，理解不了业务损失"],["优先级是否准确","比例不是标准答案，必须结合风险"],["待确认如何裁决","需要产品、开发和业务证据"],["哪些资产值得长期保留","临时规则进入公共库会制造噪声"]]}/></S>
<S id="reuse" n="08" t="先取用，再把验证过的经验回填" b="资产会越用越准"><Flow items={[["版本开始","查规则与模式库"],["测试设计","匹配并裁剪"],["执行评审","记录有效与误报"],["版本结束","回填新增资产"]]}/><Card title="回填准入"><List items={["至少在真实任务中被验证，不把一次性猜测放进公共资产。","说明适用范围和不适用范围，避免跨项目误用。","关联来源缺陷、需求或评审证据。","修改公共规则时运行历史样本回归，防止旧能力退化。"]}/></Card></S>
<S id="practice" n="09" t="为一个旧版本补齐资产链" b="练习与检查清单"><Card title="练习"><List ordered items={["选择一个已有用例但追溯不完整的模块。","把当前需求拆成规则注册表，并标出待确认项。","从历史缺陷提炼至少 3 个模式和回归检查点。","做一次新旧版本差异表与覆盖核对表。","补齐缺口后运行完整性、冲突、去重和格式检查。","输出版本总结，明确取用、修改、回归与废弃的资产。"]}/></Card><Check items={["规则是覆盖率分母","用例可追溯到版本与来源","待确认项有负责人和结论","校验能发现缺失而非只发现错误","交付物数字互相一致","回填资产经过真实验证"]}/><Next/></S>
</KnowledgeLayout></div>}

function Header(){return <header className="mb-10"><div className="mb-3 font-mono text-[10px] uppercase tracking-[0.22em] text-neon-cyan">Quality Architecture / Tutorial 23</div><h1 className="mb-3 bg-gradient-to-r from-neon-cyan to-neon-purple bg-clip-text text-3xl font-bold text-transparent md:text-4xl">测试资产工程与版本追溯教程</h1><p className="text-lg leading-8 text-text-secondary">把零散文档升级为能跨版本取用、机器校验和人工裁决的测试证据链，为自动化与 AI 辅助测试打好共同地基。</p></header>}
function S({id,n,t,b,children}:{id:string;n:string;t:string;b:string;children:React.ReactNode}){return <section id={id} data-knowledge-section className="mb-14"><div className="mb-5 flex items-center gap-3 border-b-2 border-space-border pb-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-neon-cyan/10 font-mono text-xs text-neon-cyan">{n}</div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold text-text-primary">{t}</h2><span className="rounded-full bg-neon-cyan/10 px-2 py-0.5 text-[10px] text-neon-cyan">{b}</span></div></div>{children}</section>}
function Card({title,children}:{title?:string;children:React.ReactNode}){return <div className="card-glow mb-4 rounded-xl p-5 text-sm leading-7 text-text-secondary">{title&&<h3 className="mb-3 text-base font-bold text-text-primary">{title}</h3>}{children}</div>}
function List({items,ordered=false}:{items:string[];ordered?:boolean}){const T=ordered?"ol":"ul";return <T className={`mt-3 space-y-2 pl-5 ${ordered?"list-decimal":"list-disc"}`}>{items.map(x=><li key={x}>{x}</li>)}</T>}
function Table({title,headers,rows}:{title:string;headers:string[];rows:string[][]}){return <Card title={title}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b border-space-border">{headers.map(x=><th key={x} className="bg-neon-cyan/5 px-4 py-3 text-left text-text-primary">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.join()} className="border-b border-space-border/50">{r.map((x,i)=><td key={x+i} className="px-4 py-2.5 text-xs leading-relaxed">{x}</td>)}</tr>)}</tbody></table></div></Card>}
function Callout({children}:{children:React.ReactNode}){return <div className="mb-4 border-l-2 border-neon-cyan bg-neon-cyan/5 px-5 py-4 text-sm leading-7 text-text-secondary">{children}</div>}
function Flow({items}:{items:string[][]}){return <Card title="资产流转"><div className="grid gap-3 md:grid-cols-5">{items.map((x,i)=><div key={x[0]} className={`rounded-lg border p-4 ${i===1?"border-neon-cyan/50 bg-neon-cyan/10":"border-space-border bg-space-card/50"}`}><b className="block text-xs text-text-primary">{x[0]}</b><span className="text-[11px]">{x[1]}</span></div>)}</div></Card>}
function Check({items}:{items:string[]}){return <Card title="完成检查">{items.map(x=><div key={x} className="mb-2 flex gap-2"><CheckCircle2 className="mt-1 h-4 w-4 text-neon-cyan"/>{x}</div>)}</Card>}
function Next(){return <div className="mt-8 flex justify-end border-y border-space-border py-6"><Link href="/knowledge/tutorials?track=ai-testing" className="inline-flex items-center gap-2 text-sm text-neon-cyan">下一步：把测试资产交给 AI 可靠使用<ArrowRight className="h-4 w-4"/></Link></div>}
