import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import { KnowledgeLayout, type SectionItem } from "@/components/KnowledgeLayout";
import { buildPageMetadata } from "@/lib/site";
import { cn } from "@/lib/cn";

export const metadata = buildPageMetadata({ title: "移动端 App 测试实战教程", description: "以商城 App 登录、下单、支付和退款为案例，学习安装升级、生命周期、权限、弱网、推送、深链、Android/iOS 差异与日志定位。", path: "/knowledge/mobile-app-testing", tags: ["App 测试", "移动端测试", "Android", "iOS", "ADB", "弱网测试"] });
const sections: SectionItem[] = [{ id: "model", label: "移动测试模型" }, { id: "install", label: "安装升级卸载" }, { id: "lifecycle", label: "前后台与中断" }, { id: "permission", label: "系统权限" }, { id: "network", label: "弱网与断网" }, { id: "capability", label: "推送深链扫码" }, { id: "platform", label: "Android 与 iOS" }, { id: "logs", label: "ADB 与日志" }, { id: "practice", label: "练习与检查" }];
const installRows = [["首次安装", "新设备、低存储、不同系统版本", "启动正常，不生成脏数据"], ["覆盖升级", "旧版本登录态、购物车、待支付订单", "兼容旧数据，核心状态不丢失"], ["跨版本升级", "跳过一个或多个历史版本", "迁移脚本仍能正确执行"], ["卸载重装", "本地缓存、通知权限、服务端账号", "本地数据按设计清除，服务端订单保留"]];
const platformRows = [["返回行为", "系统返回键、手势返回、Activity 栈", "导航返回手势、视图栈"], ["权限", "版本与厂商差异较多", "权限文案和系统策略更统一"], ["后台", "厂商省电可能杀进程", "系统后台时间限制严格"], ["推送", "厂商通道与系统通知设置", "APNs、专注模式和通知摘要"], ["安装", "APK/AAB、签名与渠道包", "TestFlight/企业签名与描述文件"]];

export default function MobileAppTestingPage() { return <div className="mx-auto max-w-5xl animate-fade-in">
      <Link href="/knowledge/business-state-machine-testing" className="mb-8 inline-flex items-center gap-2 text-sm text-text-secondary transition-colors hover:text-neon-cyan"><ArrowLeft className="h-4 w-4" />返回业务状态流转测试</Link>
  <KnowledgeLayout sections={sections} searchPlaceholder="搜索移动端测试关键词...">
    <header className="mb-10"><div className="mb-3 font-mono text-[10px] uppercase tracking-[0.22em] text-neon-cyan">Main Track / Tutorial 08</div><h1 className="mb-3 bg-gradient-to-r from-neon-cyan to-neon-purple bg-clip-text text-3xl font-bold text-transparent md:text-4xl">移动端 App 测试实战教程</h1><p className="mb-6 text-lg leading-8 text-text-secondary">把商城交易放进真实设备环境，验证安装升级、系统中断、权限、网络变化和平台差异下的业务连续性。</p><div className="flex flex-wrap gap-6 text-sm text-text-secondary"><span>9 个章节</span><span>Android + iOS</span><span>设备操作 + 日志证据</span></div></header>
    <section id="model" data-knowledge-section className="mb-14"><SectionHeader number="01" title="移动端比 Web 多了哪些变量" badge="业务运行在设备与系统中" /><FlowFigure id="mobile-model" title="App 结果由四层共同影响" items={[["业务状态", "订单支付退款"], ["应用状态", "前台后台与进程"], ["系统能力", "权限通知相机"], ["设备网络", "机型系统与链路"]]} /><Card title="先准备设备矩阵"><BulletList items={["按真实用户占比选择 Android/iOS 主版本与代表机型。", "覆盖高低性能、不同屏幕和至少一台真机。", "记录 App 版本、构建号、渠道、系统和网络。", "高风险支付与退款优先在目标设备组合验证。"]} /></Card><Callout>模拟器适合快速回归，但不能完全替代真机上的相机、推送、网络切换、性能、厂商系统和生物识别验证。</Callout></section>
    <section id="install" data-knowledge-section className="mb-14"><SectionHeader number="02" title="验证安装、升级与卸载" badge="版本变化不能破坏用户数据" /><TableCard title="应用生命周期场景" headers={["场景", "准备条件", "关键预期"]} rows={installRows} /><Card title="升级测试步骤"><BulletList ordered items={["安装线上或指定旧版本并登录。", "创建购物车、待支付订单和退款中订单。", "不清数据覆盖安装新版本。", "首次启动检查迁移、权限提示和崩溃。", "核对登录态、购物车与三个订单状态。", "完成一次新下单、模拟支付和退款。"]} /></Card><Card title="升级用例"><BulletList items={["当旧版本存在待支付订单时，升级后订单仍可查询且金额不变。", "当升级过程中空间不足时，安装失败不破坏原可用版本。", "当卸载后重新安装时，本地敏感信息不被错误恢复。"]} /></Card></section>
    <section id="lifecycle" data-knowledge-section className="mb-14"><SectionHeader number="03" title="测试前后台切换与系统中断" badge="随时会被打断" /><InterruptFigure /><TableCard title="支付过程中的中断" headers={["中断", "操作", "检查"]} rows={[["切到后台", "支付中按 Home，等待后恢复", "不重复支付，能查询最终结果"], ["来电/通知", "收银台被系统界面覆盖", "恢复后页面和输入状态合理"], ["锁屏", "提交订单后立即锁屏", "解锁后不重复提交且状态更新"], ["进程被杀", "后台清理 App 后重启", "从服务端恢复订单真实状态"], ["横竖屏/多窗口", "关键页面改变窗口形态", "不丢数据、不重复触发请求"]]} /><Callout>恢复页面时以服务端状态为准。不要仅凭本地“支付中”动画决定成功或失败。</Callout></section>
    <section id="permission" data-knowledge-section className="mb-14"><SectionHeader number="04" title="覆盖首次、拒绝和再次授权" badge="权限也有状态流转" /><PermissionFigure /><Card title="相机扫码退款凭证"><BulletList items={["当首次扫码时，先解释用途再请求相机权限。", "当用户拒绝相机权限时，功能给出替代上传方式。", "当用户永久拒绝时，引导到系统设置但不死循环弹窗。", "当授权后又在设置中关闭时，再次扫码能识别变化。", "当照片包含个人信息时，只申请必要访问范围并按规则清理。"]} /></Card><Callout>不要把“用户拒绝权限”当异常崩溃场景。核心交易若不依赖该权限，应当仍可继续完成。</Callout></section>
    <section id="network" data-knowledge-section className="mb-14"><SectionHeader number="05" title="在弱网、断网和网络切换中验证" badge="慢、丢、断、切" /><NetworkFigure /><TableCard title="交易弱网用例" headers={["条件", "当……时，……", "关键证据"]} rows={[["提交前断网", "当无网络提交订单时，页面提示可恢复且不生成订单", "请求未到达或明确失败"], ["响应前断网", "当订单请求已受理但响应丢失时，重试不会创建第二单", "幂等键与最终订单数"], ["支付中切网", "当 Wi-Fi 切到蜂窝网络时，App 查询支付最终结果", "支付单与订单一致"], ["高延迟", "当退款响应变慢时，按钮保持防重且允许离开后查询", "单一退款单与超时策略"]]} /><Card title="执行原则"><BulletList ordered items={["准备可清理的测试订单并记录初始状态。", "设置延迟、丢包、断网或网络切换条件。", "在请求前、发送后、响应前分别注入变化。", "恢复网络后查询服务端最终状态。", "核对重复请求、提示、重试、数据和日志。"]} /></Card></section>
    <section id="capability" data-knowledge-section className="mb-14"><SectionHeader number="06" title="测试推送、深链与扫码" badge="从系统入口回到正确业务" /><EntryFigure /><TableCard title="外部入口测试" headers={["能力", "测试点", "商城预期"]} rows={[["推送", "前台、后台、进程关闭、权限关闭", "退款进度通知准确，点击进入对应退款单"], ["深链", "已登录、未登录、链接过期、参数篡改", "登录后回到授权订单，不泄露他人信息"], ["扫码", "正常、模糊、无效、重复、相册导入", "识别安全，错误可恢复，不重复领券"], ["支付回跳", "成功、取消、App 被杀、重复回跳", "始终查询服务端结果，不仅信任回跳参数"]]} /><Callout>推送文本和深链参数都不应被视为可信业务事实。打开页面后重新鉴权并查询最新订单或退款状态。</Callout></section>
    <section id="platform" data-knowledge-section className="mb-14"><SectionHeader number="07" title="处理 Android 与 iOS 差异" badge="同一目标，不同系统行为" /><TableCard title="平台差异清单" headers={["方向", "Android", "iOS"]} rows={platformRows} /><Card title="平台用例"><BulletList items={["当 Android 用户按系统返回键离开支付页时，二次确认且不取消已受理支付。", "当 iOS 用户侧滑返回时，页面行为与导航按钮一致。", "当系统通知权限关闭时，退款进度仍可在 App 内查询。", "当低内存导致进程回收时，重启后从服务端恢复交易状态。"]} /></Card></section>
    <section id="logs" data-knowledge-section className="mb-14"><SectionHeader number="08" title="使用 ADB 与设备日志定位问题" badge="让现象有时间线" /><LogFlow /><CodeBlock title="Android 常用只读排查命令">{`adb devices
adb shell getprop ro.build.version.release
adb shell dumpsys package com.example.mall
adb logcat -c
adb logcat -v time | findstr /i "order payment refund crash"
adb shell dumpsys activity activities`}</CodeBlock><Card title="定位“支付后 App 无响应”"><BulletList ordered items={["记录设备、系统、App 版本和发生时间。", "复现前清空日志，避免旧信息干扰。", "同时记录订单号、request_id 和屏幕录制。", "检查崩溃、ANR、网络异常和 Activity 切换。", "把客户端时间线与接口、服务日志和业务数据对齐。", "分享前删除令牌、账号和个人信息。"]} /></Card><Callout>ADB 适用于已授权的测试设备。iOS 使用 Xcode Devices and Simulators 或 Console 收集对应设备日志，分析思路仍是“时间 + 业务 ID + 状态”。</Callout></section>
    <section id="practice" data-knowledge-section className="mb-14"><SectionHeader number="09" title="完成一次移动商城实战" badge="真机验证与证据闭环" /><Card title="练习"><BulletList ordered items={["选择 Android 与 iOS 各一台代表设备并记录环境。", "准备旧版本中的登录态、购物车和三种订单状态后升级。", "在支付中执行后台、锁屏、切网和杀进程。", "验证相机权限首次允许、拒绝和设置中关闭。", "验证退款推送和订单深链在登录前后的行为。", "收集一次失败的设备日志并关联请求和订单数据。", "按“当……时，……”写 12 条用例并给出结果。"]} /></Card><div className="grid gap-4 md:grid-cols-3"><ChecklistCard title="设备与版本" items={["矩阵有依据", "升级数据保留", "卸载行为明确", "平台差异已覆盖"]} /><ChecklistCard title="环境变化" items={["前后台已覆盖", "权限状态已覆盖", "弱网断网已覆盖", "进程恢复已覆盖"]} /><ChecklistCard title="业务证据" items={["请求可追踪", "状态以服务端为准", "数据没有重复", "日志已经脱敏"]} /></div><NextLink text="已经能在设备上稳定复现问题后，下一篇继续沿网络请求向下定位参数、响应与耗时。" href="/knowledge/network-packet-capture" label="继续学习抓包与网络请求分析" /></section>
  </KnowledgeLayout>
</div>; }

function SectionHeader({ number, title, badge }: { number: string; title: string; badge: string }) { return <div className="mb-5 flex items-center gap-3 border-b-2 border-space-border pb-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-neon-cyan/10 font-mono text-xs text-neon-cyan">{number}</div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold text-text-primary">{title}</h2><span className="rounded-full bg-neon-cyan/10 px-2 py-0.5 text-[10px] font-medium text-neon-cyan">{badge}</span></div></div>; }
function Card({ title, children }: { title?: string; children: React.ReactNode }) { return <div className="card-glow mb-4 rounded-xl p-5 text-sm leading-7 text-text-secondary">{title && <h3 className="mb-3 text-base font-bold text-text-primary">{title}</h3>}{children}</div>; }
function BulletList({ items, ordered = false }: { items: readonly string[]; ordered?: boolean }) { const Tag = ordered ? "ol" : "ul"; return <Tag className={cn("mt-3 space-y-2 pl-5", ordered ? "list-decimal" : "list-disc")}>{items.map((item) => <li key={item}>{item}</li>)}</Tag>; }
function TableCard({ title, headers, rows }: { title: string; headers: readonly string[]; rows: readonly string[][] }) { return <Card title={title}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b border-space-border">{headers.map((header) => <th key={header} className="bg-neon-cyan/5 px-4 py-3 text-left font-semibold text-text-primary">{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.join("-")} className="border-b border-space-border/50 last:border-b-0">{row.map((cell, index) => <td key={`${cell}-${index}`} className="px-4 py-2.5 text-xs leading-relaxed">{cell}</td>)}</tr>)}</tbody></table></div></Card>; }
function Callout({ children }: { children: React.ReactNode }) { return <div className="mb-4 border-l-2 border-neon-cyan bg-neon-cyan/5 px-5 py-4 text-sm leading-7 text-text-secondary">{children}</div>; }
function FlowFigure({ id, title, items }: { id: string; title: string; items: readonly (readonly [string, string])[] }) { return <figure className="card-glow mb-4 rounded-xl p-5" aria-labelledby={id}><figcaption id={id} className="mb-5 text-sm font-bold text-text-primary">{title}</figcaption><div className="grid gap-2 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{items.map((item, index) => <div key={item[0]} className="contents"><div className="rounded-lg border border-space-border bg-space-card/50 p-4 text-center"><strong className="block text-sm text-text-primary">{item[0]}</strong><span className="mt-2 block text-xs text-text-secondary">{item[1]}</span></div>{index < items.length - 1 && <ArrowRight className="mx-auto hidden h-4 w-4 text-neon-cyan md:block" />}</div>)}</div></figure>; }
function InterruptFigure() { return <FlowFigure id="interrupt-title" title="中断后的恢复判断" items={[["交易进行中", "记录本地状态"], ["系统中断", "后台、锁屏、来电"], ["应用恢复", "重新查询服务端"], ["继续或结束", "按真实状态展示"]]} />; }
function PermissionFigure() { return <FlowFigure id="permission-title" title="权限状态流转" items={[["未询问", "解释使用目的"], ["已允许", "使用最小权限"], ["已拒绝", "提供替代路径"], ["永久拒绝", "引导系统设置"]]} />; }
function NetworkFigure() { return <FlowFigure id="network-title" title="网络异常要覆盖不同注入时点" items={[["发送前断网", "请求未发出"], ["发送后丢包", "结果未知"], ["响应慢", "超时与等待"], ["恢复网络", "查询与幂等重试"]]} />; }
function EntryFigure() { return <FlowFigure id="entry-title" title="外部入口进入业务页面" items={[["推送/深链/扫码", "携带定位信息"], ["App 唤起", "解析安全参数"], ["身份校验", "登录与数据权限"], ["业务查询", "展示最新状态"]]} />; }
function LogFlow() { return <FlowFigure id="log-title" title="移动端问题证据链" items={[["屏幕现象", "录屏与时间"], ["设备日志", "Crash / ANR"], ["网络请求", "request_id"], ["服务与数据", "订单最终状态"]]} />; }
function CodeBlock({ title, children }: { title: string; children: string }) { return <div className="knowledge-code-block mb-4 overflow-hidden rounded-xl border border-space-border"><div className="border-b border-space-border bg-space-card/50 px-4 py-2 text-[11px] uppercase tracking-wider text-text-secondary">{title}</div><pre className="overflow-x-auto p-4 text-[13px] leading-relaxed"><code className="text-neon-cyan/80">{children}</code></pre></div>; }
function ChecklistCard({ title, items }: { title: string; items: readonly string[] }) { return <Card title={title}><ul className="space-y-3">{items.map((item) => <li key={item} className="flex items-start gap-2"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-neon-cyan" /><span>{item}</span></li>)}</ul></Card>; }
function NextLink({ text, href, label }: { text: string; href: string; label: string }) { return <div className="mt-8 flex flex-wrap items-center justify-between gap-4 border-y border-space-border py-6"><p className="text-sm text-text-secondary">{text}</p><Link href={href} className="inline-flex items-center gap-2 text-sm text-neon-cyan">{label}<ArrowRight className="h-4 w-4" /></Link></div>; }
