import Link from "next/link";
import {ArrowLeft, CheckCircle2} from "lucide-react";
import { KnowledgeLayout, type SectionItem } from "@/components/KnowledgeLayout";
import { buildPageMetadata } from "@/lib/site";

export const metadata=buildPageMetadata({title:"测试数据设计与环境治理教程",description:"从数据需求、造数方式、隔离清理和脱敏，到环境漂移、跨层一致性与自动化数据资产的完整测试数据教程。",path:"/knowledge/test-data-management",tags:["测试数据","数据治理","数据脱敏","自动化测试"]});
const sections:SectionItem[]=[{id:"value",label:"数据是前置"},{id:"lifecycle",label:"生命周期"},{id:"prepare",label:"造数方式"},{id:"boundary",label:"边界数据"},{id:"isolation",label:"隔离清理"},{id:"privacy",label:"脱敏合规"},{id:"consistency",label:"一致性"},{id:"automation",label:"自动化配合"},{id:"practice",label:"练习清单"}];

export default function TestDataPage(){return <div className="mx-auto max-w-5xl animate-fade-in"><Link href="/knowledge/tutorials?track=data-systems" className="mb-8 inline-flex items-center gap-2 text-sm text-text-secondary hover:text-neon-cyan"><ArrowLeft className="h-4 w-4"/>返回数据与分布式测试模块</Link><KnowledgeLayout sections={sections} searchPlaceholder="搜索造数、清理、脱敏与一致性...">
<Header/>
<S id="value" n="01" t="用例能否执行，先看数据是否可信" b="数据是一等公民"><Card title="常见失败"><p>用例写着“前置：用户已有 3 条反馈”，执行时却没人知道用哪个账号、怎样创建、状态是什么、测试后如何清理。问题不是少一条 SQL，而是数据准备没有进入用例设计。</p></Card><Table title="一条数据前置必须回答" headers={["问题","可执行答案"]} rows={[["谁的数据","专用账号或租户"],["多少条","精确数量，不写“若干”"],["什么状态","待处理、已完成或已作废"],["怎样创建","接口、SQL、脚本或页面"],["怎样验证","创建后查询并断言关键字段"],["怎样清理","按唯一标记回收本次数据"]]}/></S>
<S id="lifecycle" n="02" t="按生命周期管理测试数据" b="需求到回收"><Flow items={[["设计","场景与字段"],["生成","接口/SQL/脚本"],["使用","断言与留痕"],["清理","回收或重置"],["巡检","发现漂移"]]}/><Card title="数据台账"><List items={["数据集名称、用途、环境和负责人。","创建方式、唯一标记、依赖关系与有效期。","敏感等级、脱敏规则和可访问角色。","清理方式、最近验证时间和当前状态。"]}/></Card></S>
<S id="prepare" n="03" t="按场景选择造数方式" b="快不等于稳"><Table title="四种常用方式" headers={["方式","适合","风险"]} rows={[["页面操作","验证真实用户流程、小量数据","慢，容易受 UI 变化影响"],["业务接口","批量、稳定地建立业务状态","必须同时确认接口没有绕过关键规则"],["SQL","构造查询边界或修复测试环境","可能绕过业务逻辑，只在授权环境使用"],["脚本/数据工厂","参数化生成、自动清理和重复执行","需要维护字段与业务规则同步"]]}/><Callout>生产环境默认只读。任何写 SQL、批量造数和清理动作都应限定在授权测试环境，并明确影响范围与回退方式。</Callout></S>
<S id="boundary" n="04" t="边界数据要围绕业务状态构造" b="不是只改一个数字"><Table title="高价值数据组合" headers={["场景","数据准备","验证重点"]} rows={[["0 条","干净账号或清理脚本","空态、统计与分页"],["1 条","唯一记录","首条展示、详情关联"],["恰好满页","按排序字段补齐","分页边界与稳定排序"],["唯一性冲突","相同业务键两条请求","重复校验与幂等"],["状态边界","已完成/已作废记录","按钮、接口和数据不可变"],["并发提交","多线程发送相同入参","编号唯一、只产生一份业务结果"]]}/><Card title="数据必须服务判定"><p>造出“满页 20 条”只是准备；真正的测试还要说明第 21 条进入哪一页、排序是否稳定、刷新后总数是否一致。</p></Card></S>
<S id="isolation" n="05" t="用隔离和清理保证可重复" b="避免互相污染"><Table title="隔离策略" headers={["层级","做法"]} rows={[["账号/租户","每组用例使用独立账号、机构或租户"],["命名","数据带 run_id、用例号或时间批次"],["事务","可以回滚的测试在事务结束后回滚"],["资源","文件、消息和缓存使用独立前缀"],["并发","避免多个任务共享同一业务主键"]]}/><Card title="清理原则"><List items={["只删除本次 run_id 创建的数据，不用宽泛条件。","先清子表、消息、缓存与文件，再处理主记录。","清理后再次查询，确认没有残留。","清理失败应显示为测试失败或独立告警，不能静默忽略。"]}/></Card></S>
<S id="privacy" n="06" t="脱敏要换值不换测试特征" b="真实但不暴露"><Table title="脱敏校验" headers={["要求","检查"]} rows={[["不可逆","无法从脱敏值反推真实身份"],["一致性","同一实体跨表、跨字段保持可关联"],["格式有效","证件号、手机号等仍通过格式校验"],["分布保真","金额、长度、空值和长尾特征仍能支撑测试"],["最小权限","只有需要的人和系统可以访问样本"]]}/><Callout>把真实姓名统一替换成“张三”会破坏唯一性和关联测试。脱敏后的数据仍应保留长度、格式、重复关系和业务分布。</Callout></S>
<S id="consistency" n="07" t="数据准备之后还要验证四层一致" b="页面到数据库"><Table title="一致性对照" headers={["对照","常见问题"]} rows={[["列表 ↔ 详情","点开后不是同一记录或字段口径不同"],["页面 ↔ 接口","前端缓存、写死或二次计算错误"],["接口 ↔ 数据库","查错表、漏过滤条件、字段转换错误"],["主表 ↔ 附属表","状态更新了，消息或流水没有生成"],["本系统 ↔ 外部系统","全量、增量、时间窗或失败重放不一致"]]}/><Card title="状态变更的固定动作"><p>每次写操作都核对页面、详情、接口、主表和附属表。若存在异步同步，再验证处理中的中间态、最终状态和失败补偿。</p></Card></S>
<S id="automation" n="08" t="让数据准备成为自动化的一部分" b="准备、验证、清理"><Card title="用例数据四件套"><List items={["准备：调用哪个接口、SQL 或脚本，参数是什么。","标记：使用唯一 run_id，便于识别和回收。","验证：先证明数据已到位，再执行正式断言。","清理：后置步骤按 run_id 删除，并确认无残留。"]}/></Card><Table title="AI 生成用例时的约束" headers={["不要输出","应该输出"]} rows={[["前置：已有测试数据","调用数据工厂创建 3 条待处理记录并校验编号唯一"],["准备大量订单","按分页大小生成 N 条，N 来自页面配置或需求"],["使用生产数据测试","使用脱敏样本，并说明敏感字段校验方式"]]}/></S>
<S id="practice" n="09" t="完成一次可重复的数据方案" b="练习与检查清单"><Card title="练习"><List ordered items={["为一个状态流转功能列出正常、边界、异常与并发数据。","分别选择接口、SQL 或脚本造数，并说明原因。","给每组数据添加 run_id、到位断言和清理步骤。","验证页面、接口、主表、附属表四层一致。","模拟同步失败，验证重放、对账与告警。"]}/></Card><Check items={["前置数量与状态精确","造数方式可重复","测试数据彼此隔离","清理只作用于本次数据","真实数据已合规脱敏","环境漂移有巡检","跨层一致性有证据"]}/></S>
</KnowledgeLayout></div>}

function Header(){return <header className="mb-10"><div className="mb-3 font-mono text-[10px] uppercase tracking-[0.22em] text-neon-cyan">Data & Systems / Tutorial 11</div><h1 className="mb-3 bg-gradient-to-r from-neon-cyan to-neon-purple bg-clip-text text-3xl font-bold text-transparent md:text-4xl">测试数据设计与环境治理教程</h1><p className="text-lg leading-8 text-text-secondary">把“临时找几条数据”升级为可准备、可验证、可清理、可审计的工程资产，让手工测试、自动化和 AI 生成用例都能真正执行。</p></header>}
function S({id,n,t,b,children}:{id:string;n:string;t:string;b:string;children:React.ReactNode}){return <section id={id} data-knowledge-section className="mb-14"><div className="mb-5 flex items-center gap-3 border-b-2 border-space-border pb-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-neon-cyan/10 font-mono text-xs text-neon-cyan">{n}</div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold text-text-primary">{t}</h2><span className="rounded-full bg-neon-cyan/10 px-2 py-0.5 text-[10px] text-neon-cyan">{b}</span></div></div>{children}</section>}
function Card({title,children}:{title?:string;children:React.ReactNode}){return <div className="card-glow mb-4 rounded-xl p-5 text-sm leading-7 text-text-secondary">{title&&<h3 className="mb-3 text-base font-bold text-text-primary">{title}</h3>}{children}</div>}
function List({items,ordered=false}:{items:string[];ordered?:boolean}){const T=ordered?"ol":"ul";return <T className={`mt-3 space-y-2 pl-5 ${ordered?"list-decimal":"list-disc"}`}>{items.map(x=><li key={x}>{x}</li>)}</T>}
function Table({title,headers,rows}:{title:string;headers:string[];rows:string[][]}){return <Card title={title}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b border-space-border">{headers.map(x=><th key={x} className="bg-neon-cyan/5 px-4 py-3 text-left text-text-primary">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.join()} className="border-b border-space-border/50">{r.map((x,i)=><td key={x+i} className="px-4 py-2.5 text-xs leading-relaxed">{x}</td>)}</tr>)}</tbody></table></div></Card>}
function Callout({children}:{children:React.ReactNode}){return <div className="mb-4 border-l-2 border-neon-cyan bg-neon-cyan/5 px-5 py-4 text-sm leading-7 text-text-secondary">{children}</div>}
function Flow({items}:{items:string[][]}){return <Card title="测试数据生命周期"><div className="grid gap-3 md:grid-cols-5">{items.map((x,i)=><div key={x[0]} className={`rounded-lg border p-4 ${i===2?"border-neon-cyan/50 bg-neon-cyan/10":"border-space-border bg-space-card/50"}`}><b className="block text-xs text-text-primary">{x[0]}</b><span className="text-[11px]">{x[1]}</span></div>)}</div></Card>}
function Check({items}:{items:string[]}){return <Card title="完成检查">{items.map(x=><div key={x} className="mb-2 flex gap-2"><CheckCircle2 className="mt-1 h-4 w-4 text-neon-cyan"/>{x}</div>)}</Card>}
