import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import { KnowledgeLayout, type SectionItem } from "@/components/KnowledgeLayout";
import { buildPageMetadata } from "@/lib/site";

export const metadata=buildPageMetadata({title:"测试报告、效能度量与质量复盘教程",description:"围绕商城版本学习风险报告、覆盖率、缺陷分布、测试有效性、自动化收益、线上复盘与反无意义 KPI。",path:"/knowledge/test-metrics-quality-review",tags:["测试报告","质量度量","测试效能","质量复盘"]});
const sections:SectionItem[]=[{id:"decision",label:"报告目标"},{id:"coverage",label:"覆盖率"},{id:"defects",label:"缺陷分布"},{id:"effectiveness",label:"测试有效性"},{id:"automation",label:"自动化收益"},{id:"dashboard",label:"质量看板"},{id:"review",label:"质量复盘"},{id:"kpi",label:"反无意义KPI"},{id:"practice",label:"练习与清单"}];
const coverageRows=[["需求覆盖","高风险验收规则是否有验证证据","重复支付、超卖、退款失败规则覆盖"],["风险覆盖","已识别风险中被验证的比例","P0 风险必须逐项有结论"],["层级覆盖","单元、接口、集成、E2E 是否分工合理","金额规则不靠大量 UI 用例穷举"],["代码覆盖","哪些代码被执行","辅助发现盲区，不能证明断言有效"],["环境覆盖","浏览器、设备、配置、依赖组合","只覆盖风险相关组合"]];
const defectRows=[["需求阶段","规则冲突、边界遗漏","加强评审和示例化验收"],["开发阶段","状态机、幂等、异常处理","补单元与契约测试"],["测试阶段","跨服务一致性、环境差异","补集成和故障演练"],["线上阶段","长尾流量、监控盲区","补可观测性、灰度和回归"]];

export default function MetricsPage(){return <div className="mx-auto max-w-5xl animate-fade-in"><Link href="/knowledge/tutorials?track=quality-architecture" className="mb-8 inline-flex items-center gap-2 text-sm text-text-secondary hover:text-neon-cyan"><ArrowLeft className="h-4 w-4"/>返回质量体系与测试架构模块</Link><KnowledgeLayout sections={sections} searchPlaceholder="搜索报告、度量和复盘关键词...">
<header className="mb-10"><div className="mb-3 font-mono text-[10px] uppercase tracking-[0.22em] text-neon-cyan">Quality Architecture / Tutorial 22</div><h1 className="mb-3 bg-gradient-to-r from-neon-cyan to-neon-purple bg-clip-text text-3xl font-bold text-transparent md:text-4xl">测试报告、效能度量与质量复盘教程</h1><p className="mb-6 text-lg leading-8 text-text-secondary">把前一篇的线上证据转成发布判断和改进动作：不是证明测试做了很多，而是说明风险是否可接受、机制是否有效。</p><div className="flex flex-wrap gap-6 text-sm text-text-secondary"><span>9 个章节</span><span>报告 + 指标 + 复盘</span><span>反无意义 KPI</span></div></header>
<S id="decision" n="01" t="测试报告首先服务决策" b="结论先于数字"><Flow items={[["版本变化","优惠与支付回调"],["风险与范围","重复扣款、超卖"],["验证证据","用例、缺陷、指标"],["剩余风险","未测与已知问题"],["发布建议","阻断 / 有条件 / 允许"]]}/><Card title="一页报告必须回答"><List items={["测的是哪个版本、环境和时间窗口？","最重要的业务风险验证结果如何？","哪些内容失败、阻塞、未执行，为什么？","遗留问题影响谁，是否有规避、监控和负责人？","最终建议是什么，依据是什么？"]}/></Card><Callout>“执行 500 条、通过率 98%”不是发布结论。若失败的 2% 包含重复扣款，就必须阻断；若是低风险文案，可在责任明确后有条件发布。</Callout></S>
<S id="coverage" n="02" t="用多维覆盖率寻找盲区" b="覆盖不只一个百分比"><Table title="五类覆盖率" headers={["维度","回答的问题","商城例子"]} rows={coverageRows}/><Code title="风险覆盖率示意">{`risk_coverage = 已有有效验证证据的风险数 / 已识别风险数
P0_risk_coverage = 12 / 12 = 100%
P1_risk_coverage = 21 / 24 = 87.5%
# 同时列出未覆盖的 3 项，不只展示百分比`}</Code><Card title="用例：当新增“取消后自动退款”规则时，报告应显示退款风险覆盖变化"><List items={["把退款金额、重复回调、超时补偿列为独立风险。","关联接口、消息、E2E 和对账用例。","对未验证的第三方超时场景标记未覆盖，而不是默认通过。"]}/></Card></S>
<S id="defects" n="03" t="按分布与根因读懂缺陷" b="数量只是入口"><Table title="按发现阶段分析缺陷" headers={["阶段","典型问题","改进方向"]} rows={defectRows}/><Card title="至少保留这些维度"><List items={["模块、严重度、发现阶段、引入版本和发现手段。","需求、设计、编码、数据、配置、环境等根因。","用户影响、资金影响、逃逸原因和修复时长。","重复缺陷与同源缺陷聚类，避免把一个根因算成十项成绩。"]}/></Card><Callout>缺陷多不一定测试有效，也可能代表版本质量差；缺陷少不一定质量好，也可能是覆盖不足。必须结合风险、变更量、线上逃逸与历史趋势解释。</Callout></S>
<S id="effectiveness" n="04" t="衡量测试是否更早发现重要问题" b="有效性而非忙碌度"><Table title="有效性指标" headers={["指标","定义","使用边界"]} rows={[["缺陷逃逸率","线上发现缺陷 / 全部有效缺陷","按严重度和发布频率看趋势"],["阶段移除效率","某阶段发现 / 进入该阶段的问题","用于发现防线薄弱处，不评价个人"],["高风险命中率","发现高风险问题的用例 / 高风险用例","低值时审查用例设计和风险判断"],["误报率","无产品问题的失败 / 全部失败","拆分脚本、环境、数据和产品原因"],["反馈时间","变更到可靠结果的时间","同时保证结果可信，不能只求快"]]}/><Card title="用例：当自动化通过但线上出现重复退款时，应反查哪道防线失效"><List ordered items={["确认该风险是否在测试策略中被识别。","检查是否有重复消息和并发退款用例。","检查断言是否只看状态码而未核对退款流水数量。","把逃逸原因归到机制，不归咎某个人。"]}/></Card></S>
<S id="automation" n="05" t="计算自动化的真实收益" b="维护成本必须入账"><Code title="收益模型">{`saved_hours = manual_duration * useful_runs - triage_hours
net_value = saved_hours * hourly_cost - build_cost - maintenance_cost
reliable_rate = trusted_results / all_runs

# 失败无人处理、长期跳过的用例不计入有效覆盖`}</Code><Table title="不要只看自动化数量" headers={["观察项","好信号","坏信号"]} rows={[["稳定性","失败可复现且归因清楚","Flaky 导致团队默认重跑"],["反馈速度","P0 回归几分钟给出可靠结果","全量套件数小时且无人等待"],["维护投入","变更影响集中、可预测","每次 UI 微调大面积修脚本"],["缺陷价值","拦截过真实高风险回归","只验证页面能打开"],["使用频率","在 PR、发布中真正参与决策","只在汇报前运行"]]}/></S>
<S id="dashboard" n="06" t="构建能下钻的质量看板" b="趋势、分母、上下文"><Flow items={[["业务结果","成功率与线上事故"],["风险防护","P0 覆盖与门禁"],["交付效率","反馈与修复时长"],["资产健康","Flaky 与维护成本"],["下钻证据","版本、缺陷、用例"]]}/><Card title="看板验收用例"><List items={["当发布日期筛选变化时，所有图表使用同一时间范围。","当执行重跑时，同一次结果不会重复计数。","当用例被跳过时，覆盖率分母和原因可见。","当点击线上缺陷时，可下钻到版本、风险、遗漏用例和复盘。","当数据源延迟时，看板显示更新时间，不展示伪实时结果。"]}/></Card></S>
<S id="review" n="07" t="从事故时间线走向系统改进" b="复盘不追责"><Timeline/><Card title="质量复盘五问"><List ordered items={["发生了什么，用户与业务影响是什么？","为什么现有测试、门禁和告警没有更早阻止或发现？","哪些事实来自日志、Trace、数据对账，哪些仍是推测？","修复当前问题后，要补哪条需求规则、用例、监控或恢复机制？","改进项由谁在何时完成，怎样验证确实生效？"]}/></Card><Card title="用例：当支付回调重复导致重复退款时，复盘应落到防复发"><p>补充 eventId 幂等约束、重复消息集成用例、退款流水唯一性告警和上线对账，而不是只写“开发加强自测、测试认真回归”。</p></Card></S>
<S id="kpi" n="08" t="拒绝会驱动错误行为的 KPI" b="指标用于学习"><Table title="反无意义 KPI" headers={["不要这样考核","会导致什么","更好的问法"]} rows={[["每人每月发现 Bug 数","拆分缺陷、对抗协作","高风险问题是否更早被发现"],["自动化用例越多越好","重复、低价值、无人维护","哪些回归被稳定缩短或拦截"],["通过率必须 100%","隐藏跳过和已知失败","失败是否被解释并有决策"],["代码覆盖率越高越好","为数字写无断言测试","关键风险是否有有效断言"],["线上零缺陷","压制上报、漏记问题","影响是否下降、恢复是否更快"]]}/><Callout>好指标帮助团队提出问题，坏 KPI 让人优化数字。任何指标都应有清楚分母、数据来源、使用目的和配套行动，不用于脱离上下文评价个人。</Callout></S>
<S id="practice" n="09" t="交付一份可行动的质量复盘" b="练习与检查清单"><Card title="练习"><List ordered items={["为一次商城发布写一页决策报告，列出三项最高风险。","计算风险覆盖、缺陷逃逸、自动化可靠率与反馈时间。","选一个线上支付问题，画出从发生到恢复的证据时间线。","计算一组自动化用例的净收益，说明是否继续维护。","识别现有看板中两个可能被误用的 KPI，并改写为问题导向指标。","输出三项有负责人、期限和验收方式的改进动作。"]}/></Card><div className="grid gap-4 md:grid-cols-3"><Check title="报告" items={["版本范围清楚","风险结论优先","未测项可见","建议可执行"]}/><Check title="度量" items={["口径和分母明确","趋势可下钻","成本已计入","不评价个人"]}/><Check title="复盘" items={["事实与推测分开","系统根因明确","防复发可验证","负责人和期限明确"]}/></div><Next/></S>
</KnowledgeLayout></div>}

function S({id,n,t,b,children}:{id:string;n:string;t:string;b:string;children:React.ReactNode}){return <section id={id} data-knowledge-section className="mb-14"><div className="mb-5 flex items-center gap-3 border-b-2 border-space-border pb-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-neon-cyan/10 font-mono text-xs text-neon-cyan">{n}</div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold text-text-primary">{t}</h2><span className="rounded-full bg-neon-cyan/10 px-2 py-0.5 text-[10px] text-neon-cyan">{b}</span></div></div>{children}</section>}
function Card({title,children}:{title?:string;children:React.ReactNode}){return <div className="card-glow mb-4 rounded-xl p-5 text-sm leading-7 text-text-secondary">{title&&<h3 className="mb-3 text-base font-bold text-text-primary">{title}</h3>}{children}</div>}
function List({items,ordered=false}:{items:string[];ordered?:boolean}){const T=ordered?"ol":"ul";return <T className={`mt-3 space-y-2 pl-5 ${ordered?"list-decimal":"list-disc"}`}>{items.map(x=><li key={x}>{x}</li>)}</T>}
function Table({title,headers,rows}:{title:string;headers:string[];rows:string[][]}){return <Card title={title}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b border-space-border">{headers.map(x=><th key={x} className="bg-neon-cyan/5 px-4 py-3 text-left text-text-primary">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.join()} className="border-b border-space-border/50">{r.map((x,i)=><td key={x+i} className="px-4 py-2.5 text-xs leading-relaxed">{x}</td>)}</tr>)}</tbody></table></div></Card>}
function Code({title,children}:{title:string;children:string}){return <div className="knowledge-code-block mb-4 overflow-hidden rounded-xl border border-space-border"><div className="border-b border-space-border bg-space-card/50 px-4 py-2 text-xs text-text-secondary">{title}</div><pre className="overflow-x-auto p-4 text-[13px]"><code className="text-neon-cyan/80">{children}</code></pre></div>}
function Callout({children}:{children:React.ReactNode}){return <div className="mb-4 border-l-2 border-neon-cyan bg-neon-cyan/5 px-5 py-4 text-sm leading-7 text-text-secondary">{children}</div>}
function Flow({items}:{items:string[][]}){return <Card title="从数据到决策的链路"><div className="grid gap-2 md:grid-cols-9 md:items-center">{items.map((x,i)=><div className="contents" key={x[0]}><div className="rounded-lg border border-space-border bg-space-card/50 p-4 text-center"><b className="block text-xs text-text-primary">{x[0]}</b><span className="text-[11px]">{x[1]}</span></div>{i<4&&<ArrowRight className="mx-auto hidden h-4 w-4 text-neon-cyan md:block"/>}</div>)}</div></Card>}
function Timeline(){return <Card title="线上支付问题复盘时间线"><div className="grid gap-3 md:grid-cols-4">{[["发现","支付告警与投诉"],["止损","关闭重试开关"],["恢复","补偿订单并对账"],["防复发","幂等约束 + 回归"]].map(x=><div key={x[0]} className="rounded-lg border border-space-border bg-space-card/50 p-4"><b className="text-neon-cyan">{x[0]}</b><p className="mt-2 text-xs">{x[1]}</p></div>)}</div></Card>}
function Check({title,items}:{title:string;items:string[]}){return <Card title={title}><ul className="space-y-3">{items.map(x=><li key={x} className="flex gap-2"><CheckCircle2 className="mt-1 h-4 w-4 text-neon-cyan"/>{x}</li>)}</ul></Card>}
function Next(){return <div className="mt-8 flex justify-end border-y border-space-border py-6"><Link href="/knowledge" className="inline-flex items-center gap-2 text-sm text-neon-cyan">主线完成：选择一条强化支线<ArrowRight className="h-4 w-4"/></Link></div>}
